// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Gemv_Test_Mul_Adder_Tree_128_Loop_adder_2_1_proc_8_Pipeline_adder_2_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pass_2_i_dout,
        pass_2_i_empty_n,
        pass_2_i_read,
        pass_2_i_num_data_valid,
        pass_2_i_fifo_cap,
        adder_tree_output_0_din,
        adder_tree_output_0_full_n,
        adder_tree_output_0_write,
        adder_tree_output_0_num_data_valid,
        adder_tree_output_0_fifo_cap,
        select_ln59
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] pass_2_i_dout;
input   pass_2_i_empty_n;
output   pass_2_i_read;
input  [2:0] pass_2_i_num_data_valid;
input  [2:0] pass_2_i_fifo_cap;
output  [31:0] adder_tree_output_0_din;
input   adder_tree_output_0_full_n;
output   adder_tree_output_0_write;
input  [31:0] adder_tree_output_0_num_data_valid;
input  [31:0] adder_tree_output_0_fifo_cap;
input  [22:0] select_ln59;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln182_fu_177_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    pass_2_i_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    adder_tree_output_0_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] trunc_ln185_fu_196_p1;
reg   [15:0] trunc_ln185_reg_974;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [15:0] trunc_ln185_1_reg_979;
wire   [0:0] tmp_fu_238_p3;
reg   [0:0] tmp_reg_994;
reg   [0:0] tmp_reg_994_pp0_iter5_reg;
wire   [53:0] select_ln195_fu_280_p3;
reg   [53:0] select_ln195_reg_1003;
wire   [0:0] icmp_ln195_fu_288_p2;
reg   [0:0] icmp_ln195_reg_1010;
reg   [0:0] icmp_ln195_reg_1010_pp0_iter5_reg;
wire   [11:0] sub_ln195_1_fu_294_p2;
reg   [11:0] sub_ln195_1_reg_1016;
wire   [0:0] icmp_ln195_1_fu_308_p2;
reg   [0:0] icmp_ln195_1_reg_1022;
wire   [10:0] select_ln195_1_fu_330_p3;
reg   [10:0] select_ln195_1_reg_1027;
wire   [31:0] trunc_ln195_13_fu_338_p1;
reg   [31:0] trunc_ln195_13_reg_1034;
wire   [0:0] icmp_ln195_4_fu_342_p2;
reg   [0:0] icmp_ln195_4_reg_1040;
wire   [0:0] icmp_ln195_17_fu_358_p2;
reg   [0:0] icmp_ln195_17_reg_1045;
wire   [0:0] tmp_548_fu_370_p3;
reg   [0:0] tmp_548_reg_1050;
wire   [0:0] icmp_ln195_18_fu_406_p2;
reg   [0:0] icmp_ln195_18_reg_1055;
reg   [0:0] icmp_ln195_18_reg_1055_pp0_iter5_reg;
wire   [0:0] icmp_ln195_7_fu_422_p2;
reg   [0:0] icmp_ln195_7_reg_1060;
reg   [0:0] icmp_ln195_7_reg_1060_pp0_iter5_reg;
reg   [0:0] tmp_553_reg_1067;
reg   [0:0] tmp_553_reg_1067_pp0_iter5_reg;
wire   [0:0] lD_0_i_i_fu_450_p2;
reg   [0:0] lD_0_i_i_reg_1074;
wire   [31:0] ref_tmp_i_i_0_i_fu_564_p9;
reg   [31:0] ref_tmp_i_i_0_i_reg_1081;
wire   [0:0] carry_1_i_i_fu_589_p2;
reg   [0:0] carry_1_i_i_reg_1086;
reg   [0:0] tmp_552_reg_1093;
wire   [0:0] Range2_all_ones_1_i_i_fu_664_p3;
reg   [0:0] Range2_all_ones_1_i_i_reg_1100;
wire   [0:0] xor_ln195_1_fu_683_p2;
reg   [0:0] xor_ln195_1_reg_1105;
wire   [0:0] Range1_all_ones_2_i_i_fu_742_p9;
reg   [0:0] Range1_all_ones_2_i_i_reg_1110;
wire   [0:0] Range1_all_zeros_2_i_i_fu_761_p9;
reg   [0:0] Range1_all_zeros_2_i_i_reg_1117;
reg   [21:0] iter_fu_134;
wire   [21:0] add_ln182_fu_183_p2;
wire    ap_loop_init;
reg   [21:0] ap_sig_allocacmp_iter_load;
wire    ap_block_pp0_stage0;
reg    pass_2_i_read_local;
wire   [31:0] ref_tmp_i_i_4_i_fu_939_p9;
reg    ap_block_pp0_stage0_01001_grp1;
reg    adder_tree_output_0_write_local;
wire   [15:0] grp_fu_157_p0;
wire   [15:0] grp_fu_157_p1;
wire   [15:0] grp_fu_157_p2;
wire   [22:0] iter_cast_fu_173_p1;
wire   [63:0] pf_fu_161_p1;
wire   [63:0] bitcast_ln735_fu_230_p1;
wire   [10:0] tmp_1_fu_246_p3;
wire   [51:0] trunc_ln195_9_fu_258_p1;
wire   [52:0] zext_ln195_1_cast_fu_262_p3;
wire   [53:0] zext_ln195_6_fu_270_p1;
wire   [53:0] sub_ln195_fu_274_p2;
wire   [62:0] trunc_ln195_fu_234_p1;
wire   [11:0] zext_ln195_fu_254_p1;
wire   [11:0] add_ln195_fu_314_p2;
wire   [10:0] trunc_ln195_11_fu_304_p1;
wire   [10:0] trunc_ln195_12_fu_320_p1;
wire   [10:0] sub_ln195_2_fu_324_p2;
wire   [5:0] tmp_547_fu_348_p4;
wire   [5:0] trunc_ln195_10_fu_300_p1;
wire   [5:0] tmp_548_fu_370_p2;
wire   [10:0] or_ln195_4_fu_378_p3;
wire  signed [11:0] sext_ln195_fu_386_p1;
wire   [11:0] add_ln195_3_fu_390_p2;
wire   [7:0] tmp_551_fu_396_p4;
wire   [11:0] add_ln195_4_fu_412_p2;
wire   [5:0] tobool130_i_i_fu_442_p2;
wire   [0:0] icmp_ln195_9_fu_436_p2;
wire   [0:0] tobool130_i_i_fu_442_p3;
wire   [53:0] zext_ln195_2_fu_476_p1;
wire   [53:0] ashr_ln195_fu_479_p2;
wire   [0:0] icmp_ln195_3_fu_464_p2;
wire   [31:0] trunc_ln195_14_fu_484_p1;
wire   [31:0] select_ln195_7_fu_469_p3;
wire   [31:0] zext_ln195_4_fu_456_p1;
wire   [31:0] shl_ln195_fu_496_p2;
wire   [31:0] select_ln195_2_fu_488_p3;
wire   [0:0] cond63_i_i_fu_508_p3;
wire   [31:0] zext_ln195_3_fu_521_p1;
wire   [31:0] add_ln195_2_fu_525_p2;
wire   [0:0] tmp_550_fu_531_p3;
wire   [0:0] icmp_ln195_2_fu_459_p2;
wire   [0:0] xor_ln195_2_fu_545_p2;
wire   [0:0] and_ln195_9_fu_551_p2;
wire   [31:0] ref_tmp_i_i_0_i_fu_564_p6;
wire   [31:0] ref_tmp_i_i_0_i_fu_564_p7;
wire   [1:0] ref_tmp_i_i_0_i_fu_564_p8;
wire   [0:0] tmp_549_fu_513_p3;
wire   [0:0] and_ln195_10_fu_583_p2;
wire   [0:0] xor_ln195_fu_539_p2;
wire   [11:0] add_ln195_5_fu_595_p2;
wire   [5:0] trunc_ln195_16_fu_625_p1;
wire   [53:0] zext_ln195_5_fu_629_p1;
wire   [53:0] lshr_ln195_fu_633_p2;
wire   [53:0] lshr_ln195_1_fu_638_p2;
wire   [0:0] tmp_554_fu_650_p3;
wire   [0:0] icmp_ln195_11_fu_619_p2;
wire   [0:0] icmp_ln195_12_fu_644_p2;
wire   [0:0] xor_ln195_12_fu_658_p2;
wire   [0:0] icmp_ln195_10_fu_613_p2;
wire   [0:0] xor_ln195_11_fu_608_p2;
wire   [0:0] icmp_ln195_14_fu_688_p2;
wire   [0:0] icmp_ln195_16_fu_706_p2;
wire   [0:0] xor_ln195_13_fu_717_p2;
wire   [0:0] icmp_ln195_15_fu_700_p2;
wire   [0:0] or_ln195_5_fu_723_p2;
wire   [0:0] and_ln195_1_fu_672_p2;
wire   [0:0] and_ln195_11_fu_728_p2;
wire   [0:0] Range1_all_ones_2_i_i_fu_742_p2;
wire   [0:0] Range1_all_ones_2_i_i_fu_742_p7;
wire   [1:0] sel_tmp_fu_734_p3;
wire   [0:0] Range1_all_zeros_2_i_i_fu_761_p2;
wire   [0:0] Range1_all_zeros_2_i_i_fu_761_p6;
wire   [0:0] Range1_all_zeros_2_i_i_fu_761_p7;
wire   [0:0] or_ln195_1_fu_790_p2;
wire   [0:0] and_ln195_4_fu_794_p2;
wire   [0:0] and_ln195_5_fu_805_p2;
wire   [0:0] cond189_i_i_fu_799_p3;
wire   [0:0] not_icmp_ln195_735_fu_815_p2;
wire   [0:0] and_ln195_12_fu_826_p2;
wire   [0:0] neg_src_0_i_i_fu_838_p2;
wire   [0:0] neg_src_0_i_i_fu_838_p4;
wire   [0:0] neg_src_0_i_i_fu_838_p7;
wire   [1:0] neg_src_0_i_i_fu_838_p8;
wire   [0:0] select_ln195_4_fu_785_p3;
wire   [0:0] xor_ln195_5_fu_858_p2;
wire   [0:0] and_ln195_13_fu_864_p2;
wire   [0:0] or_ln195_2_fu_869_p2;
wire   [0:0] xor_ln195_6_fu_874_p2;
wire   [0:0] deleted_ones_0_i_i_fu_820_p2;
wire   [0:0] and_ln195_7_fu_885_p2;
wire   [0:0] neg_src_0_i_i_fu_838_p9;
wire   [0:0] xor_ln195_7_fu_890_p2;
wire   [0:0] and_ln195_8_fu_896_p2;
wire   [0:0] and_ln195_6_fu_879_p2;
wire   [0:0] or_ln195_3_fu_902_p2;
wire   [0:0] xor_ln195_8_fu_916_p2;
wire   [0:0] and_ln195_14_fu_921_p2;
wire   [0:0] and_ln195_15_fu_927_p2;
wire   [31:0] ref_tmp_i_i_4_i_fu_939_p4;
wire   [31:0] ref_tmp_i_i_4_i_fu_939_p7;
wire   [1:0] ref_tmp_i_i_4_i_fu_939_p8;
reg    grp_fu_157_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [0:0] tmp_548_fu_370_p0;
wire   [0:0] tobool130_i_i_fu_442_p0;
wire  signed [1:0] ref_tmp_i_i_0_i_fu_564_p1;
wire   [1:0] ref_tmp_i_i_0_i_fu_564_p3;
wire   [1:0] ref_tmp_i_i_0_i_fu_564_p5;
wire  signed [1:0] Range1_all_ones_2_i_i_fu_742_p1;
wire   [1:0] Range1_all_ones_2_i_i_fu_742_p3;
wire   [1:0] Range1_all_ones_2_i_i_fu_742_p5;
wire  signed [1:0] Range1_all_zeros_2_i_i_fu_761_p1;
wire   [1:0] Range1_all_zeros_2_i_i_fu_761_p3;
wire   [1:0] Range1_all_zeros_2_i_i_fu_761_p5;
wire  signed [1:0] neg_src_0_i_i_fu_838_p1;
wire   [1:0] neg_src_0_i_i_fu_838_p3;
wire   [1:0] neg_src_0_i_i_fu_838_p5;
wire  signed [1:0] ref_tmp_i_i_4_i_fu_939_p1;
wire   [1:0] ref_tmp_i_i_4_i_fu_939_p3;
wire   [1:0] ref_tmp_i_i_4_i_fu_939_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 iter_fu_134 = 22'd0;
#0 ap_done_reg = 1'b0;
end

Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_3_no_dsp_1_U661(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_157_p0),
    .din1(grp_fu_157_p1),
    .ce(grp_fu_157_ce),
    .dout(grp_fu_157_p2)
);

Gemv_Test_hptodp_16ns_64_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 64 ))
hptodp_16ns_64_1_no_dsp_1_U662(
    .din0(grp_fu_157_p2),
    .dout(pf_fu_161_p1)
);

Gemv_Test_bitselect_1ns_54ns_6ns_1_1_1 #(
    .DATAWIDTH( 54 ),
    .ADDRWIDTH( 6 ))
bitselect_1ns_54ns_6ns_1_1_1_U663(
    .din(select_ln195_fu_280_p3),
    .sel(tmp_548_fu_370_p2),
    .dout(tmp_548_fu_370_p3)
);

Gemv_Test_bitselect_1ns_54ns_6ns_1_1_1 #(
    .DATAWIDTH( 54 ),
    .ADDRWIDTH( 6 ))
bitselect_1ns_54ns_6ns_1_1_1_U664(
    .din(select_ln195_fu_280_p3),
    .sel(tobool130_i_i_fu_442_p2),
    .dout(tobool130_i_i_fu_442_p3)
);

(* dissolve_hierarchy = "yes" *) Gemv_Test_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U665(
    .din0(trunc_ln195_13_reg_1034),
    .din1(add_ln195_2_fu_525_p2),
    .din2(ref_tmp_i_i_0_i_fu_564_p6),
    .def(ref_tmp_i_i_0_i_fu_564_p7),
    .sel(ref_tmp_i_i_0_i_fu_564_p8),
    .dout(ref_tmp_i_i_0_i_fu_564_p9)
);

(* dissolve_hierarchy = "yes" *) Gemv_Test_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U666(
    .din0(Range1_all_ones_2_i_i_fu_742_p2),
    .din1(lD_0_i_i_reg_1074),
    .din2(xor_ln195_11_fu_608_p2),
    .def(Range1_all_ones_2_i_i_fu_742_p7),
    .sel(sel_tmp_fu_734_p3),
    .dout(Range1_all_ones_2_i_i_fu_742_p9)
);

(* dissolve_hierarchy = "yes" *) Gemv_Test_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U667(
    .din0(Range1_all_zeros_2_i_i_fu_761_p2),
    .din1(xor_ln195_1_fu_683_p2),
    .din2(Range1_all_zeros_2_i_i_fu_761_p6),
    .def(Range1_all_zeros_2_i_i_fu_761_p7),
    .sel(sel_tmp_fu_734_p3),
    .dout(Range1_all_zeros_2_i_i_fu_761_p9)
);

(* dissolve_hierarchy = "yes" *) Gemv_Test_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U668(
    .din0(neg_src_0_i_i_fu_838_p2),
    .din1(neg_src_0_i_i_fu_838_p4),
    .din2(1'd0),
    .def(neg_src_0_i_i_fu_838_p7),
    .sel(neg_src_0_i_i_fu_838_p8),
    .dout(neg_src_0_i_i_fu_838_p9)
);

(* dissolve_hierarchy = "yes" *) Gemv_Test_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U669(
    .din0(32'd0),
    .din1(ref_tmp_i_i_4_i_fu_939_p4),
    .din2(ref_tmp_i_i_0_i_reg_1081),
    .def(ref_tmp_i_i_4_i_fu_939_p7),
    .sel(ref_tmp_i_i_4_i_fu_939_p8),
    .dout(ref_tmp_i_i_4_i_fu_939_p9)
);

Gemv_Test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln182_fu_177_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            iter_fu_134 <= add_ln182_fu_183_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            iter_fu_134 <= 22'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        Range1_all_ones_2_i_i_reg_1110 <= Range1_all_ones_2_i_i_fu_742_p9;
        Range1_all_zeros_2_i_i_reg_1117 <= Range1_all_zeros_2_i_i_fu_761_p9;
        Range2_all_ones_1_i_i_reg_1100 <= Range2_all_ones_1_i_i_fu_664_p3;
        carry_1_i_i_reg_1086 <= carry_1_i_i_fu_589_p2;
        icmp_ln195_17_reg_1045 <= icmp_ln195_17_fu_358_p2;
        icmp_ln195_18_reg_1055 <= icmp_ln195_18_fu_406_p2;
        icmp_ln195_18_reg_1055_pp0_iter5_reg <= icmp_ln195_18_reg_1055;
        icmp_ln195_1_reg_1022 <= icmp_ln195_1_fu_308_p2;
        icmp_ln195_4_reg_1040 <= icmp_ln195_4_fu_342_p2;
        icmp_ln195_7_reg_1060 <= icmp_ln195_7_fu_422_p2;
        icmp_ln195_7_reg_1060_pp0_iter5_reg <= icmp_ln195_7_reg_1060;
        icmp_ln195_reg_1010 <= icmp_ln195_fu_288_p2;
        icmp_ln195_reg_1010_pp0_iter5_reg <= icmp_ln195_reg_1010;
        lD_0_i_i_reg_1074 <= lD_0_i_i_fu_450_p2;
        ref_tmp_i_i_0_i_reg_1081 <= ref_tmp_i_i_0_i_fu_564_p9;
        select_ln195_1_reg_1027 <= select_ln195_1_fu_330_p3;
        select_ln195_reg_1003 <= select_ln195_fu_280_p3;
        sub_ln195_1_reg_1016 <= sub_ln195_1_fu_294_p2;
        tmp_548_reg_1050 <= tmp_548_fu_370_p3;
        tmp_552_reg_1093 <= ref_tmp_i_i_0_i_fu_564_p9[32'd31];
        tmp_553_reg_1067 <= add_ln195_4_fu_412_p2[32'd11];
        tmp_553_reg_1067_pp0_iter5_reg <= tmp_553_reg_1067;
        tmp_reg_994 <= bitcast_ln735_fu_230_p1[32'd63];
        tmp_reg_994_pp0_iter5_reg <= tmp_reg_994;
        trunc_ln195_13_reg_1034 <= trunc_ln195_13_fu_338_p1;
        xor_ln195_1_reg_1105 <= xor_ln195_1_fu_683_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln185_1_reg_979 <= {{pass_2_i_dout[31:16]}};
        trunc_ln185_reg_974 <= trunc_ln185_fu_196_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        adder_tree_output_0_blk_n = adder_tree_output_0_full_n;
    end else begin
        adder_tree_output_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        adder_tree_output_0_write_local = 1'b1;
    end else begin
        adder_tree_output_0_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln182_fu_177_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_iter_load = 22'd0;
    end else begin
        ap_sig_allocacmp_iter_load = iter_fu_134;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_157_ce = 1'b1;
    end else begin
        grp_fu_157_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pass_2_i_blk_n = pass_2_i_empty_n;
    end else begin
        pass_2_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pass_2_i_read_local = 1'b1;
    end else begin
        pass_2_i_read_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Range1_all_ones_2_i_i_fu_742_p2 = (lD_0_i_i_reg_1074 & Range2_all_ones_1_i_i_fu_664_p3);

assign Range1_all_ones_2_i_i_fu_742_p7 = 'bx;

assign Range1_all_zeros_2_i_i_fu_761_p2 = (xor_ln195_1_fu_683_p2 & icmp_ln195_14_fu_688_p2);

assign Range1_all_zeros_2_i_i_fu_761_p6 = (xor_ln195_11_fu_608_p2 | icmp_ln195_16_fu_706_p2);

assign Range1_all_zeros_2_i_i_fu_761_p7 = 'bx;

assign Range2_all_ones_1_i_i_fu_664_p3 = ((icmp_ln195_11_fu_619_p2[0:0] == 1'b1) ? icmp_ln195_12_fu_644_p2 : xor_ln195_12_fu_658_p2);

assign add_ln182_fu_183_p2 = (ap_sig_allocacmp_iter_load + 22'd1);

assign add_ln195_2_fu_525_p2 = (select_ln195_2_fu_488_p3 + zext_ln195_3_fu_521_p1);

assign add_ln195_3_fu_390_p2 = ($signed(sext_ln195_fu_386_p1) + $signed(zext_ln195_fu_254_p1));

assign add_ln195_4_fu_412_p2 = (sub_ln195_1_fu_294_p2 + 12'd16);

assign add_ln195_5_fu_595_p2 = (sub_ln195_1_reg_1016 + 12'd17);

assign add_ln195_fu_314_p2 = ($signed(sub_ln195_1_fu_294_p2) + $signed(12'd4080));

assign adder_tree_output_0_din = ref_tmp_i_i_4_i_fu_939_p9;

assign adder_tree_output_0_write = adder_tree_output_0_write_local;

assign and_ln195_10_fu_583_p2 = (tmp_549_fu_513_p3 & and_ln195_9_fu_551_p2);

assign and_ln195_11_fu_728_p2 = (or_ln195_5_fu_723_p2 & icmp_ln195_15_fu_700_p2);

assign and_ln195_12_fu_826_p2 = (tmp_reg_994_pp0_iter5_reg & icmp_ln195_7_reg_1060_pp0_iter5_reg);

assign and_ln195_13_fu_864_p2 = (xor_ln195_5_fu_858_p2 & icmp_ln195_7_reg_1060_pp0_iter5_reg);

assign and_ln195_14_fu_921_p2 = (xor_ln195_8_fu_916_p2 & or_ln195_3_fu_902_p2);

assign and_ln195_15_fu_927_p2 = (icmp_ln195_18_reg_1055_pp0_iter5_reg & and_ln195_14_fu_921_p2);

assign and_ln195_1_fu_672_p2 = (xor_ln195_11_fu_608_p2 & icmp_ln195_10_fu_613_p2);

assign and_ln195_4_fu_794_p2 = (or_ln195_1_fu_790_p2 & Range2_all_ones_1_i_i_reg_1100);

assign and_ln195_5_fu_805_p2 = (carry_1_i_i_reg_1086 & Range1_all_ones_2_i_i_reg_1110);

assign and_ln195_6_fu_879_p2 = (xor_ln195_6_fu_874_p2 & or_ln195_2_fu_869_p2);

assign and_ln195_7_fu_885_p2 = (tmp_552_reg_1093 & deleted_ones_0_i_i_fu_820_p2);

assign and_ln195_8_fu_896_p2 = (xor_ln195_7_fu_890_p2 & neg_src_0_i_i_fu_838_p9);

assign and_ln195_9_fu_551_p2 = (xor_ln195_2_fu_545_p2 & icmp_ln195_1_reg_1022);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == adder_tree_output_0_full_n)) | ((pass_2_i_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == adder_tree_output_0_full_n)) | ((pass_2_i_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == adder_tree_output_0_full_n)) | ((pass_2_i_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == adder_tree_output_0_full_n)) | ((pass_2_i_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign ashr_ln195_fu_479_p2 = $signed(select_ln195_reg_1003) >>> zext_ln195_2_fu_476_p1;

assign bitcast_ln735_fu_230_p1 = pf_fu_161_p1;

assign carry_1_i_i_fu_589_p2 = (xor_ln195_fu_539_p2 & and_ln195_10_fu_583_p2);

assign cond189_i_i_fu_799_p3 = ((carry_1_i_i_reg_1086[0:0] == 1'b1) ? and_ln195_4_fu_794_p2 : Range1_all_ones_2_i_i_reg_1110);

assign cond63_i_i_fu_508_p3 = ((icmp_ln195_4_reg_1040[0:0] == 1'b1) ? tmp_reg_994 : tmp_548_reg_1050);

assign deleted_ones_0_i_i_fu_820_p2 = (not_icmp_ln195_735_fu_815_p2 | cond189_i_i_fu_799_p3);

assign grp_fu_157_p0 = trunc_ln185_reg_974;

assign grp_fu_157_p1 = trunc_ln185_1_reg_979;

assign icmp_ln182_fu_177_p2 = (($signed(iter_cast_fu_173_p1) < $signed(select_ln59)) ? 1'b1 : 1'b0);

assign icmp_ln195_10_fu_613_p2 = (($signed(add_ln195_5_fu_595_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln195_11_fu_619_p2 = ((add_ln195_5_fu_595_p2 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln195_12_fu_644_p2 = ((lshr_ln195_fu_633_p2 == lshr_ln195_1_fu_638_p2) ? 1'b1 : 1'b0);

assign icmp_ln195_14_fu_688_p2 = ((lshr_ln195_fu_633_p2 == 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln195_15_fu_700_p2 = ((add_ln195_5_fu_595_p2 == 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln195_16_fu_706_p2 = ((select_ln195_reg_1003 == 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln195_17_fu_358_p2 = ((tmp_547_fu_348_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln195_18_fu_406_p2 = (($signed(tmp_551_fu_396_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln195_1_fu_308_p2 = (($signed(sub_ln195_1_fu_294_p2) > $signed(12'd16)) ? 1'b1 : 1'b0);

assign icmp_ln195_2_fu_459_p2 = ((sub_ln195_1_reg_1016 == 12'd16) ? 1'b1 : 1'b0);

assign icmp_ln195_3_fu_464_p2 = ((select_ln195_1_reg_1027 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln195_4_fu_342_p2 = (($signed(add_ln195_fu_314_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln195_7_fu_422_p2 = (($signed(add_ln195_4_fu_412_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln195_9_fu_436_p2 = ((add_ln195_4_fu_412_p2 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln195_fu_288_p2 = ((trunc_ln195_fu_234_p1 == 63'd0) ? 1'b1 : 1'b0);

assign iter_cast_fu_173_p1 = ap_sig_allocacmp_iter_load;

assign lD_0_i_i_fu_450_p2 = (tobool130_i_i_fu_442_p3 & icmp_ln195_9_fu_436_p2);

assign lshr_ln195_1_fu_638_p2 = 54'd18014398509481983 >> zext_ln195_5_fu_629_p1;

assign lshr_ln195_fu_633_p2 = select_ln195_reg_1003 >> zext_ln195_5_fu_629_p1;

assign neg_src_0_i_i_fu_838_p2 = (tmp_reg_994_pp0_iter5_reg & tmp_552_reg_1093);

assign neg_src_0_i_i_fu_838_p4 = (1'd1 ^ and_ln195_5_fu_805_p2);

assign neg_src_0_i_i_fu_838_p7 = 'bx;

assign neg_src_0_i_i_fu_838_p8 = {{not_icmp_ln195_735_fu_815_p2}, {and_ln195_12_fu_826_p2}};

assign not_icmp_ln195_735_fu_815_p2 = (icmp_ln195_7_reg_1060_pp0_iter5_reg ^ 1'd1);

assign or_ln195_1_fu_790_p2 = (xor_ln195_1_reg_1105 | tmp_553_reg_1067_pp0_iter5_reg);

assign or_ln195_2_fu_869_p2 = (tmp_552_reg_1093 | and_ln195_13_fu_864_p2);

assign or_ln195_3_fu_902_p2 = (and_ln195_8_fu_896_p2 | and_ln195_6_fu_879_p2);

assign or_ln195_4_fu_378_p3 = {{10'd513}, {icmp_ln195_1_fu_308_p2}};

assign or_ln195_5_fu_723_p2 = (xor_ln195_13_fu_717_p2 | tmp_553_reg_1067);

assign pass_2_i_read = pass_2_i_read_local;

assign ref_tmp_i_i_0_i_fu_564_p6 = ((icmp_ln195_17_reg_1045[0:0] == 1'b1) ? shl_ln195_fu_496_p2 : 32'd0);

assign ref_tmp_i_i_0_i_fu_564_p7 = 'bx;

assign ref_tmp_i_i_0_i_fu_564_p8 = {{icmp_ln195_2_fu_459_p2}, {and_ln195_9_fu_551_p2}};

assign ref_tmp_i_i_4_i_fu_939_p4 = ((and_ln195_6_fu_879_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign ref_tmp_i_i_4_i_fu_939_p7 = 'bx;

assign ref_tmp_i_i_4_i_fu_939_p8 = {{icmp_ln195_reg_1010_pp0_iter5_reg}, {and_ln195_15_fu_927_p2}};

assign sel_tmp_fu_734_p3 = {{and_ln195_1_fu_672_p2}, {and_ln195_11_fu_728_p2}};

assign select_ln195_1_fu_330_p3 = ((icmp_ln195_1_fu_308_p2[0:0] == 1'b1) ? trunc_ln195_12_fu_320_p1 : sub_ln195_2_fu_324_p2);

assign select_ln195_2_fu_488_p3 = ((icmp_ln195_3_fu_464_p2[0:0] == 1'b1) ? trunc_ln195_14_fu_484_p1 : select_ln195_7_fu_469_p3);

assign select_ln195_4_fu_785_p3 = ((carry_1_i_i_reg_1086[0:0] == 1'b1) ? Range1_all_ones_2_i_i_reg_1110 : Range1_all_zeros_2_i_i_reg_1117);

assign select_ln195_7_fu_469_p3 = ((tmp_reg_994[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign select_ln195_fu_280_p3 = ((tmp_fu_238_p3[0:0] == 1'b1) ? sub_ln195_fu_274_p2 : zext_ln195_6_fu_270_p1);

assign sext_ln195_fu_386_p1 = $signed(or_ln195_4_fu_378_p3);

assign shl_ln195_fu_496_p2 = trunc_ln195_13_reg_1034 << zext_ln195_4_fu_456_p1;

assign sub_ln195_1_fu_294_p2 = (12'd1075 - zext_ln195_fu_254_p1);

assign sub_ln195_2_fu_324_p2 = (11'd16 - trunc_ln195_11_fu_304_p1);

assign sub_ln195_fu_274_p2 = (54'd0 - zext_ln195_6_fu_270_p1);

assign tmp_1_fu_246_p3 = {{bitcast_ln735_fu_230_p1[62:52]}};

assign tmp_547_fu_348_p4 = {{select_ln195_1_fu_330_p3[10:5]}};

assign tmp_548_fu_370_p2 = ($signed(trunc_ln195_10_fu_300_p1) + $signed(6'd47));

assign tmp_549_fu_513_p3 = select_ln195_2_fu_488_p3[32'd31];

assign tmp_550_fu_531_p3 = add_ln195_2_fu_525_p2[32'd31];

assign tmp_551_fu_396_p4 = {{add_ln195_3_fu_390_p2[11:4]}};

assign tmp_554_fu_650_p3 = add_ln195_5_fu_595_p2[32'd11];

assign tmp_fu_238_p3 = bitcast_ln735_fu_230_p1[32'd63];

assign tobool130_i_i_fu_442_p2 = add_ln195_4_fu_412_p2[5:0];

assign trunc_ln185_fu_196_p1 = pass_2_i_dout[15:0];

assign trunc_ln195_10_fu_300_p1 = sub_ln195_1_fu_294_p2[5:0];

assign trunc_ln195_11_fu_304_p1 = sub_ln195_1_fu_294_p2[10:0];

assign trunc_ln195_12_fu_320_p1 = add_ln195_fu_314_p2[10:0];

assign trunc_ln195_13_fu_338_p1 = select_ln195_fu_280_p3[31:0];

assign trunc_ln195_14_fu_484_p1 = ashr_ln195_fu_479_p2[31:0];

assign trunc_ln195_16_fu_625_p1 = add_ln195_5_fu_595_p2[5:0];

assign trunc_ln195_9_fu_258_p1 = bitcast_ln735_fu_230_p1[51:0];

assign trunc_ln195_fu_234_p1 = bitcast_ln735_fu_230_p1[62:0];

assign xor_ln195_11_fu_608_p2 = (tmp_553_reg_1067 ^ 1'd1);

assign xor_ln195_12_fu_658_p2 = (tmp_554_fu_650_p3 ^ 1'd1);

assign xor_ln195_13_fu_717_p2 = (icmp_ln195_10_fu_613_p2 ^ 1'd1);

assign xor_ln195_1_fu_683_p2 = (lD_0_i_i_reg_1074 ^ 1'd1);

assign xor_ln195_2_fu_545_p2 = (icmp_ln195_2_fu_459_p2 ^ 1'd1);

assign xor_ln195_5_fu_858_p2 = (select_ln195_4_fu_785_p3 ^ 1'd1);

assign xor_ln195_6_fu_874_p2 = (tmp_reg_994_pp0_iter5_reg ^ 1'd1);

assign xor_ln195_7_fu_890_p2 = (1'd1 ^ and_ln195_7_fu_885_p2);

assign xor_ln195_8_fu_916_p2 = (icmp_ln195_reg_1010_pp0_iter5_reg ^ 1'd1);

assign xor_ln195_fu_539_p2 = (tmp_550_fu_531_p3 ^ 1'd1);

assign zext_ln195_1_cast_fu_262_p3 = {{1'd1}, {trunc_ln195_9_fu_258_p1}};

assign zext_ln195_2_fu_476_p1 = select_ln195_1_reg_1027;

assign zext_ln195_3_fu_521_p1 = cond63_i_i_fu_508_p3;

assign zext_ln195_4_fu_456_p1 = select_ln195_1_reg_1027;

assign zext_ln195_5_fu_629_p1 = trunc_ln195_16_fu_625_p1;

assign zext_ln195_6_fu_270_p1 = zext_ln195_1_cast_fu_262_p3;

assign zext_ln195_fu_254_p1 = tmp_1_fu_246_p3;

endmodule //Gemv_Test_Mul_Adder_Tree_128_Loop_adder_2_1_proc_8_Pipeline_adder_2_1
