// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Softmax_Loop_max_value_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        seq_len,
        max_value_stream_din,
        max_value_stream_full_n,
        max_value_stream_write,
        max_value_stream_num_data_valid,
        max_value_stream_fifo_cap,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        max_bypass_stream_din,
        max_bypass_stream_full_n,
        max_bypass_stream_write,
        max_bypass_stream_num_data_valid,
        max_bypass_stream_fifo_cap,
        seq_len_c1_din,
        seq_len_c1_full_n,
        seq_len_c1_write,
        seq_len_c1_num_data_valid,
        seq_len_c1_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] seq_len;
output  [15:0] max_value_stream_din;
input   max_value_stream_full_n;
output   max_value_stream_write;
input  [7:0] max_value_stream_num_data_valid;
input  [7:0] max_value_stream_fifo_cap;
input  [15:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
output  [15:0] max_bypass_stream_din;
input   max_bypass_stream_full_n;
output   max_bypass_stream_write;
input  [14:0] max_bypass_stream_num_data_valid;
input  [14:0] max_bypass_stream_fifo_cap;
output  [31:0] seq_len_c1_din;
input   seq_len_c1_full_n;
output   seq_len_c1_write;
input  [2:0] seq_len_c1_num_data_valid;
input  [2:0] seq_len_c1_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    max_value_stream_blk_n;
wire    ap_CS_fsm_state4;
reg    seq_len_c1_blk_n;
reg   [31:0] seq_len_read_reg_173;
reg    ap_block_state1;
wire    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start;
wire    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_done;
wire    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_idle;
wire    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_ready;
wire   [15:0] grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_din;
wire    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_write;
wire    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_in_stream_TREADY;
wire   [15:0] grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_val_2_out;
wire    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_val_2_out_ap_vld;
reg    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln38_fu_129_p2;
wire    ap_CS_fsm_state3;
reg   [2:0] head_fu_72;
wire   [2:0] head_6_fu_123_p2;
reg    seq_len_c1_write_local;
wire   [15:0] bitcast_ln48_fu_157_p1;
reg    max_value_stream_write_local;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_in_stream_U_apdone_blk;
wire   [15:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg = 1'b0;
#0 head_fu_72 = 3'd0;
end

Softmax_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1 grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start),
    .ap_done(grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_done),
    .ap_idle(grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_idle),
    .ap_ready(grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .max_bypass_stream_din(grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_din),
    .max_bypass_stream_full_n(max_bypass_stream_full_n),
    .max_bypass_stream_write(grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_write),
    .max_bypass_stream_num_data_valid(15'd0),
    .max_bypass_stream_fifo_cap(15'd0),
    .seq_len(seq_len_read_reg_173),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_in_stream_TREADY),
    .max_val_2_out(grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_val_2_out),
    .max_val_2_out_ap_vld(grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_val_2_out_ap_vld)
);

Softmax_regslice_both #(
    .DataWidth( 16 ))
regslice_both_in_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln38_fu_129_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln38_fu_129_p2 == 1'd0))) begin
            grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg <= 1'b1;
        end else if ((grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_ready == 1'b1)) begin
            grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        head_fu_72 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln38_fu_129_p2 == 1'd0))) begin
        head_fu_72 <= head_6_fu_123_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        seq_len_read_reg_173 <= seq_len;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((max_value_stream_full_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln38_fu_129_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln38_fu_129_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        max_value_stream_blk_n = max_value_stream_full_n;
    end else begin
        max_value_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((max_value_stream_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        max_value_stream_write_local = 1'b1;
    end else begin
        max_value_stream_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        seq_len_c1_blk_n = seq_len_c1_full_n;
    end else begin
        seq_len_c1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        seq_len_c1_write_local = 1'b1;
    end else begin
        seq_len_c1_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln38_fu_129_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((max_value_stream_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((seq_len_c1_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bitcast_ln48_fu_157_p1 = grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_val_2_out;

assign grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start = grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg;

assign head_6_fu_123_p2 = (head_fu_72 + 3'd1);

assign icmp_ln38_fu_129_p2 = ((head_fu_72 == 3'd4) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_U_ack_in;

assign max_bypass_stream_din = grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_din;

assign max_bypass_stream_write = grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_write;

assign max_value_stream_din = bitcast_ln48_fu_157_p1;

assign max_value_stream_write = max_value_stream_write_local;

assign seq_len_c1_din = seq_len;

assign seq_len_c1_write = seq_len_c1_write_local;

assign start_out = real_start;

endmodule //Softmax_Loop_max_value_proc
