-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Gemv_Test_Accumulator_Quantizer_7 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    rows_empty_n : IN STD_LOGIC;
    rows_read : OUT STD_LOGIC;
    rows_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    rows_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    cols_empty_n : IN STD_LOGIC;
    cols_read : OUT STD_LOGIC;
    cols_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    cols_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    adder_tree_output_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    adder_tree_output_2_empty_n : IN STD_LOGIC;
    adder_tree_output_2_read : OUT STD_LOGIC;
    adder_tree_output_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    adder_tree_output_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    scale_dispacher_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    scale_dispacher_2_empty_n : IN STD_LOGIC;
    scale_dispacher_2_read : OUT STD_LOGIC;
    scale_dispacher_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    scale_dispacher_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    dequantized_output_2_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    dequantized_output_2_full_n : IN STD_LOGIC;
    dequantized_output_2_write : OUT STD_LOGIC;
    dequantized_output_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dequantized_output_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of Gemv_Test_Accumulator_Quantizer_7 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv29_1 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_35 : STD_LOGIC_VECTOR (5 downto 0) := "110101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_34 : STD_LOGIC_VECTOR (5 downto 0) := "110100";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal rows_blk_n : STD_LOGIC;
    signal cols_blk_n : STD_LOGIC;
    signal dequantized_output_2_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal rows_4_fu_207_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal rows_4_reg_598 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal cols_3_fu_255_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal cols_3_reg_603 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln45_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_611 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_603_fu_314_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_603_reg_616 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln45_fu_328_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln45_reg_621 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln45_fu_344_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln45_reg_629 : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln45_2_reg_635 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_607_reg_640 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_start : STD_LOGIC;
    signal grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_done : STD_LOGIC;
    signal grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_idle : STD_LOGIC;
    signal grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_ready : STD_LOGIC;
    signal grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_adder_tree_output_2_read : STD_LOGIC;
    signal grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_scale_dispacher_2_read : STD_LOGIC;
    signal grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_acc_result_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_acc_result_out_ap_vld : STD_LOGIC;
    signal grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln11_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal r_fu_126 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    signal add_ln11_fu_271_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal cols_read_local : STD_LOGIC;
    signal rows_read_local : STD_LOGIC;
    signal empty_fu_573_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal dequantized_output_2_write_local : STD_LOGIC;
    signal sub_ln73_fu_175_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_181_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_fu_167_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln73_8_fu_191_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_7_fu_197_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal sub_ln73_9_fu_223_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_229_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_602_fu_215_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln73_10_fu_239_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_9_fu_245_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln73_fu_277_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sub_ln45_fu_322_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_336_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_336_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln45_fu_348_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln45_3_fu_351_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln45_fu_361_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_604_fu_371_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln45_5_fu_357_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln45_6_fu_387_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln45_4_fu_393_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln45_3_fu_397_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln45_fu_403_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln45_4_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_5_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_605_fu_420_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_606_fu_434_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_606_fu_434_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln45_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_ln45_2_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_ln45_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln45_fu_447_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln45_4_fu_463_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln45_fu_469_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln45_4_fu_478_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln45_2_fu_484_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln45_fu_473_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln45_fu_488_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln45_6_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln45_7_fu_493_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln45_8_fu_497_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_3_fu_501_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_2_fu_453_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln45_5_fu_509_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln45_5_fu_543_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln45_4_fu_536_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln45_6_fu_548_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln45_3_fu_533_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_554_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_11_fu_561_p5 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal tmp_10_fu_336_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_606_fu_434_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component Gemv_Test_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        adder_tree_output_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        adder_tree_output_2_empty_n : IN STD_LOGIC;
        adder_tree_output_2_read : OUT STD_LOGIC;
        adder_tree_output_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        adder_tree_output_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        scale_dispacher_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        scale_dispacher_2_empty_n : IN STD_LOGIC;
        scale_dispacher_2_read : OUT STD_LOGIC;
        scale_dispacher_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        scale_dispacher_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        cols_3 : IN STD_LOGIC_VECTOR (24 downto 0);
        acc_result_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_result_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Gemv_Test_ctlz_32_32_1_1 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Gemv_Test_bitselect_1ns_32ns_5ns_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153 : component Gemv_Test_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_start,
        ap_done => grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_done,
        ap_idle => grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_idle,
        ap_ready => grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_ready,
        adder_tree_output_2_dout => adder_tree_output_2_dout,
        adder_tree_output_2_empty_n => adder_tree_output_2_empty_n,
        adder_tree_output_2_read => grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_adder_tree_output_2_read,
        adder_tree_output_2_num_data_valid => ap_const_lv3_0,
        adder_tree_output_2_fifo_cap => ap_const_lv3_0,
        scale_dispacher_2_dout => scale_dispacher_2_dout,
        scale_dispacher_2_empty_n => scale_dispacher_2_empty_n,
        scale_dispacher_2_read => grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_scale_dispacher_2_read,
        scale_dispacher_2_num_data_valid => ap_const_lv3_0,
        scale_dispacher_2_fifo_cap => ap_const_lv3_0,
        cols_3 => cols_3_reg_603,
        acc_result_out => grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_acc_result_out,
        acc_result_out_ap_vld => grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_acc_result_out_ap_vld);

    ctlz_32_32_1_1_U1940 : component Gemv_Test_ctlz_32_32_1_1
    generic map (
        din_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din => tmp_10_fu_336_p1,
        dout => tmp_10_fu_336_p3);

    bitselect_1ns_32ns_5ns_1_1_1_U1941 : component Gemv_Test_bitselect_1ns_32ns_5ns_1_1_1
    generic map (
        DATAWIDTH => 32,
        ADDRWIDTH => 5)
    port map (
        din => select_ln45_reg_621,
        sel => tmp_606_fu_434_p2,
        dout => tmp_606_fu_434_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_281_p2 = ap_const_lv1_0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_281_p2 = ap_const_lv1_1))) then 
                    grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_ready = ap_const_logic_1)) then 
                    grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    r_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                r_fu_126 <= ap_const_lv29_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_281_p2 = ap_const_lv1_1))) then 
                r_fu_126 <= add_ln11_fu_271_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                cols_3_reg_603 <= cols_3_fu_255_p3;
                rows_4_reg_598 <= rows_4_fu_207_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln45_reg_611 <= icmp_ln45_fu_308_p2;
                select_ln45_reg_621 <= select_ln45_fu_328_p3;
                tmp_603_reg_616 <= grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_acc_result_out(31 downto 31);
                trunc_ln45_reg_629 <= trunc_ln45_fu_344_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                lshr_ln45_2_reg_635 <= add_ln45_5_fu_509_p2(15 downto 1);
                tmp_607_reg_640 <= add_ln45_5_fu_509_p2(12 downto 12);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, dequantized_output_2_full_n, ap_CS_fsm_state6, ap_block_state1, grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_done, ap_CS_fsm_state2, icmp_ln11_fu_281_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_281_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((dequantized_output_2_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln11_fu_271_p2 <= std_logic_vector(unsigned(r_fu_126) + unsigned(ap_const_lv29_1));
    add_ln45_4_fu_463_p2 <= std_logic_vector(unsigned(sub_ln45_3_fu_351_p2) + unsigned(ap_const_lv6_34));
    add_ln45_5_fu_509_p2 <= std_logic_vector(unsigned(select_ln45_3_fu_501_p3) + unsigned(zext_ln45_2_fu_453_p1));
    add_ln45_6_fu_548_p2 <= std_logic_vector(unsigned(sub_ln45_5_fu_543_p2) + unsigned(select_ln45_4_fu_536_p3));
    add_ln45_fu_361_p2 <= std_logic_vector(unsigned(sub_ln45_3_fu_351_p2) + unsigned(ap_const_lv6_35));
    adder_tree_output_2_read <= grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_adder_tree_output_2_read;
    and_ln45_fu_403_p2 <= (select_ln45_reg_621 and lshr_ln45_3_fu_397_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_done)
    begin
        if ((grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(dequantized_output_2_full_n)
    begin
        if ((dequantized_output_2_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, rows_empty_n, cols_empty_n)
    begin
                ap_block_state1 <= ((cols_empty_n = ap_const_logic_0) or (rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln11_fu_281_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_281_p2 = ap_const_lv1_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln11_fu_281_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_281_p2 = ap_const_lv1_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cols_3_fu_255_p3 <= 
        sub_ln73_10_fu_239_p2 when (tmp_602_fu_215_p3(0) = '1') else 
        tmp_9_fu_245_p4;

    cols_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, cols_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cols_blk_n <= cols_empty_n;
        else 
            cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    cols_read <= cols_read_local;

    cols_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cols_read_local <= ap_const_logic_1;
        else 
            cols_read_local <= ap_const_logic_0;
        end if; 
    end process;


    dequantized_output_2_blk_n_assign_proc : process(dequantized_output_2_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            dequantized_output_2_blk_n <= dequantized_output_2_full_n;
        else 
            dequantized_output_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dequantized_output_2_din <= empty_fu_573_p3;
    dequantized_output_2_write <= dequantized_output_2_write_local;

    dequantized_output_2_write_local_assign_proc : process(dequantized_output_2_full_n, ap_CS_fsm_state6)
    begin
        if (((dequantized_output_2_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            dequantized_output_2_write_local <= ap_const_logic_1;
        else 
            dequantized_output_2_write_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_573_p3 <= 
        ap_const_lv16_0 when (icmp_ln45_reg_611(0) = '1') else 
        tmp_11_fu_561_p5;
    grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_start <= grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_ap_start_reg;
    icmp_ln11_fu_281_p2 <= "1" when (signed(zext_ln73_fu_277_p1) < signed(rows_4_reg_598)) else "0";
    icmp_ln45_4_fu_381_p2 <= "1" when (signed(tmp_604_fu_371_p4) > signed(ap_const_lv5_0)) else "0";
    icmp_ln45_5_fu_408_p2 <= "0" when (and_ln45_fu_403_p2 = ap_const_lv32_0) else "1";
    icmp_ln45_6_fu_457_p2 <= "1" when (signed(add_ln45_fu_361_p2) > signed(ap_const_lv6_0)) else "0";
    icmp_ln45_fu_308_p2 <= "1" when (grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_acc_result_out = ap_const_lv32_0) else "0";
    lshr_ln45_3_fu_397_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv32_FFFFFFFF),to_integer(unsigned('0' & zext_ln45_4_fu_393_p1(31-1 downto 0)))));
    lshr_ln45_fu_473_p2 <= std_logic_vector(shift_right(unsigned(select_ln45_reg_621),to_integer(unsigned('0' & sext_ln45_fu_469_p1(31-1 downto 0)))));
    or_ln45_fu_447_p2 <= (phi_ln45_fu_414_p2 or phi_ln45_2_fu_441_p2);
    phi_ln45_2_fu_441_p2 <= (xor_ln45_fu_428_p2 and tmp_606_fu_434_p3);
    phi_ln45_fu_414_p2 <= (icmp_ln45_5_fu_408_p2 and icmp_ln45_4_fu_381_p2);
    rows_4_fu_207_p3 <= 
        sub_ln73_8_fu_191_p2 when (tmp_fu_167_p3(0) = '1') else 
        tmp_7_fu_197_p4;

    rows_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, rows_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rows_blk_n <= rows_empty_n;
        else 
            rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rows_read <= rows_read_local;

    rows_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rows_read_local <= ap_const_logic_1;
        else 
            rows_read_local <= ap_const_logic_0;
        end if; 
    end process;

    scale_dispacher_2_read <= grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_scale_dispacher_2_read;
    select_ln45_3_fu_501_p3 <= 
        trunc_ln45_7_fu_493_p1 when (icmp_ln45_6_fu_457_p2(0) = '1') else 
        trunc_ln45_8_fu_497_p1;
    select_ln45_4_fu_536_p3 <= 
        ap_const_lv5_F when (tmp_607_reg_640(0) = '1') else 
        ap_const_lv5_E;
    select_ln45_fu_328_p3 <= 
        sub_ln45_fu_322_p2 when (tmp_603_fu_314_p3(0) = '1') else 
        grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_acc_result_out;
        sext_ln45_2_fu_484_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln45_4_fu_478_p2),32));

        sext_ln45_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln45_4_fu_463_p2),32));

    shl_ln45_fu_488_p2 <= std_logic_vector(shift_left(unsigned(select_ln45_reg_621),to_integer(unsigned('0' & sext_ln45_2_fu_484_p1(31-1 downto 0)))));
    sub_ln45_3_fu_351_p2 <= std_logic_vector(signed(ap_const_lv6_20) - signed(zext_ln45_fu_348_p1));
    sub_ln45_4_fu_478_p2 <= std_logic_vector(unsigned(ap_const_lv6_C) - unsigned(sub_ln45_3_fu_351_p2));
    sub_ln45_5_fu_543_p2 <= std_logic_vector(signed(ap_const_lv5_10) - signed(trunc_ln45_reg_629));
    sub_ln45_6_fu_387_p2 <= std_logic_vector(unsigned(ap_const_lv5_C) - unsigned(trunc_ln45_5_fu_357_p1));
    sub_ln45_fu_322_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_acc_result_out));
    sub_ln73_10_fu_239_p2 <= std_logic_vector(unsigned(ap_const_lv25_0) - unsigned(tmp_8_fu_229_p4));
    sub_ln73_8_fu_191_p2 <= std_logic_vector(unsigned(ap_const_lv30_0) - unsigned(tmp_s_fu_181_p4));
    sub_ln73_9_fu_223_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(cols_dout));
    sub_ln73_fu_175_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(rows_dout));
    tmp_10_fu_336_p1 <= 
        sub_ln45_fu_322_p2 when (tmp_603_fu_314_p3(0) = '1') else 
        grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_acc_result_out;
    tmp_11_fu_561_p5 <= (tmp_4_fu_554_p3 & zext_ln45_3_fu_533_p1(9 downto 0));
    tmp_4_fu_554_p3 <= (tmp_603_reg_616 & add_ln45_6_fu_548_p2);
    tmp_602_fu_215_p3 <= cols_dout(31 downto 31);
    tmp_603_fu_314_p3 <= grp_Accumulator_Quantizer_7_Pipeline_VITIS_LOOP_17_2_fu_153_acc_result_out(31 downto 31);
    tmp_604_fu_371_p4 <= add_ln45_fu_361_p2(5 downto 1);
    tmp_605_fu_420_p3 <= add_ln45_fu_361_p2(5 downto 5);
    tmp_606_fu_434_p2 <= add_ln45_fu_361_p2(5 - 1 downto 0);
    tmp_7_fu_197_p4 <= rows_dout(31 downto 2);
    tmp_8_fu_229_p4 <= sub_ln73_9_fu_223_p2(31 downto 7);
    tmp_9_fu_245_p4 <= cols_dout(31 downto 7);
    tmp_fu_167_p3 <= rows_dout(31 downto 31);
    tmp_s_fu_181_p4 <= sub_ln73_fu_175_p2(31 downto 2);
    trunc_ln45_5_fu_357_p1 <= sub_ln45_3_fu_351_p2(5 - 1 downto 0);
    trunc_ln45_7_fu_493_p1 <= lshr_ln45_fu_473_p2(16 - 1 downto 0);
    trunc_ln45_8_fu_497_p1 <= shl_ln45_fu_488_p2(16 - 1 downto 0);
    trunc_ln45_fu_344_p1 <= tmp_10_fu_336_p3(5 - 1 downto 0);
    xor_ln45_fu_428_p2 <= (tmp_605_fu_420_p3 xor ap_const_lv1_1);
    zext_ln45_2_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln45_fu_447_p2),16));
    zext_ln45_3_fu_533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln45_2_reg_635),16));
    zext_ln45_4_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln45_6_fu_387_p2),32));
    zext_ln45_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln45_reg_629),6));
    zext_ln73_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_126),30));
end behav;
