-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Gemv_Test_Scale_Loader_Distributor_Pipeline_load_from_hbm is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    scale_dispacher_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    scale_dispacher_0_full_n : IN STD_LOGIC;
    scale_dispacher_0_write : OUT STD_LOGIC;
    scale_dispacher_0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    scale_dispacher_0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    scale_dispacher_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    scale_dispacher_1_full_n : IN STD_LOGIC;
    scale_dispacher_1_write : OUT STD_LOGIC;
    scale_dispacher_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    scale_dispacher_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    scale_dispacher_2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    scale_dispacher_2_full_n : IN STD_LOGIC;
    scale_dispacher_2_write : OUT STD_LOGIC;
    scale_dispacher_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    scale_dispacher_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    scale_dispacher_3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    scale_dispacher_3_full_n : IN STD_LOGIC;
    scale_dispacher_3_write : OUT STD_LOGIC;
    scale_dispacher_3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    scale_dispacher_3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Iterations : IN STD_LOGIC_VECTOR (20 downto 0);
    empty : IN STD_LOGIC_VECTOR (31 downto 0);
    data_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_14 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of Gemv_Test_Scale_Loader_Distributor_Pipeline_load_from_hbm is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv20_1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln24_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal scale_dispacher_0_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal scale_dispacher_1_blk_n : STD_LOGIC;
    signal scale_dispacher_2_blk_n : STD_LOGIC;
    signal scale_dispacher_3_blk_n : STD_LOGIC;
    signal iter_fu_84 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal add_ln24_fu_236_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_iter_load : STD_LOGIC_VECTOR (19 downto 0);
    signal scale_dispacher_0_din_local : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal scale_dispacher_0_write_local : STD_LOGIC;
    signal scale_dispacher_1_din_local : STD_LOGIC_VECTOR (31 downto 0);
    signal scale_dispacher_1_write_local : STD_LOGIC;
    signal scale_dispacher_2_din_local : STD_LOGIC_VECTOR (31 downto 0);
    signal scale_dispacher_2_write_local : STD_LOGIC;
    signal scale_dispacher_3_din_local : STD_LOGIC_VECTOR (31 downto 0);
    signal scale_dispacher_3_write_local : STD_LOGIC;
    signal zext_ln24_fu_226_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Gemv_Test_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component Gemv_Test_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    iter_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln24_fu_230_p2 = ap_const_lv1_1)) then 
                    iter_fu_84 <= add_ln24_fu_236_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    iter_fu_84 <= ap_const_lv20_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln24_fu_230_p2, ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln24_fu_230_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln24_fu_236_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_iter_load) + unsigned(ap_const_lv20_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_pp0_stage1_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_pp0_stage2_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4_pp0_stage3_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5_pp0_stage4_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(scale_dispacher_0_full_n, scale_dispacher_1_full_n, scale_dispacher_2_full_n, scale_dispacher_3_full_n)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((scale_dispacher_3_full_n = ap_const_logic_0) or (scale_dispacher_2_full_n = ap_const_logic_0) or (scale_dispacher_1_full_n = ap_const_logic_0) or (scale_dispacher_0_full_n = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(scale_dispacher_0_full_n, scale_dispacher_1_full_n, scale_dispacher_2_full_n, scale_dispacher_3_full_n)
    begin
                ap_block_state3_pp0_stage2_iter0 <= ((scale_dispacher_3_full_n = ap_const_logic_0) or (scale_dispacher_2_full_n = ap_const_logic_0) or (scale_dispacher_1_full_n = ap_const_logic_0) or (scale_dispacher_0_full_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage3_iter0_assign_proc : process(scale_dispacher_0_full_n, scale_dispacher_1_full_n, scale_dispacher_2_full_n, scale_dispacher_3_full_n)
    begin
                ap_block_state4_pp0_stage3_iter0 <= ((scale_dispacher_3_full_n = ap_const_logic_0) or (scale_dispacher_2_full_n = ap_const_logic_0) or (scale_dispacher_1_full_n = ap_const_logic_0) or (scale_dispacher_0_full_n = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage4_iter0_assign_proc : process(scale_dispacher_0_full_n, scale_dispacher_1_full_n, scale_dispacher_2_full_n, scale_dispacher_3_full_n)
    begin
                ap_block_state5_pp0_stage4_iter0 <= ((scale_dispacher_3_full_n = ap_const_logic_0) or (scale_dispacher_2_full_n = ap_const_logic_0) or (scale_dispacher_1_full_n = ap_const_logic_0) or (scale_dispacher_0_full_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln24_fu_230_p2)
    begin
        if (((icmp_ln24_fu_230_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_iter_load_assign_proc : process(ap_CS_fsm_state1, iter_fu_84, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_iter_load <= ap_const_lv20_0;
        else 
            ap_sig_allocacmp_iter_load <= iter_fu_84;
        end if; 
    end process;

    icmp_ln24_fu_230_p2 <= "1" when (signed(zext_ln24_fu_226_p1) < signed(Iterations)) else "0";

    scale_dispacher_0_blk_n_assign_proc : process(ap_CS_fsm_state5, scale_dispacher_0_full_n, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            scale_dispacher_0_blk_n <= scale_dispacher_0_full_n;
        else 
            scale_dispacher_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    scale_dispacher_0_din <= scale_dispacher_0_din_local;

    scale_dispacher_0_din_local_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0, empty, data_4, data_8, data_11, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            scale_dispacher_0_din_local <= data_11;
        elsif (((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            scale_dispacher_0_din_local <= data_8;
        elsif (((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            scale_dispacher_0_din_local <= data_4;
        elsif (((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            scale_dispacher_0_din_local <= empty;
        else 
            scale_dispacher_0_din_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    scale_dispacher_0_write <= scale_dispacher_0_write_local;

    scale_dispacher_0_write_local_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        if ((((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            scale_dispacher_0_write_local <= ap_const_logic_1;
        else 
            scale_dispacher_0_write_local <= ap_const_logic_0;
        end if; 
    end process;


    scale_dispacher_1_blk_n_assign_proc : process(ap_CS_fsm_state5, scale_dispacher_1_full_n, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            scale_dispacher_1_blk_n <= scale_dispacher_1_full_n;
        else 
            scale_dispacher_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    scale_dispacher_1_din <= scale_dispacher_1_din_local;

    scale_dispacher_1_din_local_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0, data_1, data_5, data_9, data_12, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            scale_dispacher_1_din_local <= data_12;
        elsif (((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            scale_dispacher_1_din_local <= data_9;
        elsif (((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            scale_dispacher_1_din_local <= data_5;
        elsif (((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            scale_dispacher_1_din_local <= data_1;
        else 
            scale_dispacher_1_din_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    scale_dispacher_1_write <= scale_dispacher_1_write_local;

    scale_dispacher_1_write_local_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        if ((((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            scale_dispacher_1_write_local <= ap_const_logic_1;
        else 
            scale_dispacher_1_write_local <= ap_const_logic_0;
        end if; 
    end process;


    scale_dispacher_2_blk_n_assign_proc : process(ap_CS_fsm_state5, scale_dispacher_2_full_n, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            scale_dispacher_2_blk_n <= scale_dispacher_2_full_n;
        else 
            scale_dispacher_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    scale_dispacher_2_din <= scale_dispacher_2_din_local;

    scale_dispacher_2_din_local_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0, data_2, data_6, data_15, data_13, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            scale_dispacher_2_din_local <= data_13;
        elsif (((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            scale_dispacher_2_din_local <= data_15;
        elsif (((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            scale_dispacher_2_din_local <= data_6;
        elsif (((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            scale_dispacher_2_din_local <= data_2;
        else 
            scale_dispacher_2_din_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    scale_dispacher_2_write <= scale_dispacher_2_write_local;

    scale_dispacher_2_write_local_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        if ((((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            scale_dispacher_2_write_local <= ap_const_logic_1;
        else 
            scale_dispacher_2_write_local <= ap_const_logic_0;
        end if; 
    end process;


    scale_dispacher_3_blk_n_assign_proc : process(ap_CS_fsm_state5, scale_dispacher_3_full_n, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            scale_dispacher_3_blk_n <= scale_dispacher_3_full_n;
        else 
            scale_dispacher_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    scale_dispacher_3_din <= scale_dispacher_3_din_local;

    scale_dispacher_3_din_local_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0, data_3, data_7, data_10, data_14, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            scale_dispacher_3_din_local <= data_14;
        elsif (((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            scale_dispacher_3_din_local <= data_10;
        elsif (((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            scale_dispacher_3_din_local <= data_7;
        elsif (((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            scale_dispacher_3_din_local <= data_3;
        else 
            scale_dispacher_3_din_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    scale_dispacher_3_write <= scale_dispacher_3_write_local;

    scale_dispacher_3_write_local_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        if ((((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            scale_dispacher_3_write_local <= ap_const_logic_1;
        else 
            scale_dispacher_3_write_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln24_fu_226_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_iter_load),21));
end behav;
