-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Softmax_Loop_max_value_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    seq_len : IN STD_LOGIC_VECTOR (31 downto 0);
    max_value_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    max_value_stream_full_n : IN STD_LOGIC;
    max_value_stream_write : OUT STD_LOGIC;
    max_value_stream_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    max_value_stream_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    max_bypass_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    max_bypass_stream_full_n : IN STD_LOGIC;
    max_bypass_stream_write : OUT STD_LOGIC;
    max_bypass_stream_num_data_valid : IN STD_LOGIC_VECTOR (14 downto 0);
    max_bypass_stream_fifo_cap : IN STD_LOGIC_VECTOR (14 downto 0);
    seq_len_c1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    seq_len_c1_full_n : IN STD_LOGIC;
    seq_len_c1_write : OUT STD_LOGIC;
    seq_len_c1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    seq_len_c1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of Softmax_Loop_max_value_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal max_value_stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal seq_len_c1_blk_n : STD_LOGIC;
    signal seq_len_read_reg_173 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start : STD_LOGIC;
    signal grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_done : STD_LOGIC;
    signal grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_idle : STD_LOGIC;
    signal grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_ready : STD_LOGIC;
    signal grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_din : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_write : STD_LOGIC;
    signal grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_in_stream_TREADY : STD_LOGIC;
    signal grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_val_2_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_val_2_out_ap_vld : STD_LOGIC;
    signal grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln38_fu_129_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal head_fu_72 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal head_6_fu_123_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal seq_len_c1_write_local : STD_LOGIC;
    signal bitcast_ln48_fu_157_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal max_value_stream_write_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal regslice_both_in_stream_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Softmax_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        max_bypass_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        max_bypass_stream_full_n : IN STD_LOGIC;
        max_bypass_stream_write : OUT STD_LOGIC;
        max_bypass_stream_num_data_valid : IN STD_LOGIC_VECTOR (14 downto 0);
        max_bypass_stream_fifo_cap : IN STD_LOGIC_VECTOR (14 downto 0);
        seq_len : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        max_val_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        max_val_2_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Softmax_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101 : component Softmax_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start,
        ap_done => grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_done,
        ap_idle => grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_idle,
        ap_ready => grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        max_bypass_stream_din => grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_din,
        max_bypass_stream_full_n => max_bypass_stream_full_n,
        max_bypass_stream_write => grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_write,
        max_bypass_stream_num_data_valid => ap_const_lv15_0,
        max_bypass_stream_fifo_cap => ap_const_lv15_0,
        seq_len => seq_len_read_reg_173,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_in_stream_TREADY,
        max_val_2_out => grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_val_2_out,
        max_val_2_out_ap_vld => grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_val_2_out_ap_vld);

    regslice_both_in_stream_U : component Softmax_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln38_fu_129_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln38_fu_129_p2 = ap_const_lv1_0))) then 
                    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_ready = ap_const_logic_1)) then 
                    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    head_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                head_fu_72 <= ap_const_lv3_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln38_fu_129_p2 = ap_const_lv1_0))) then 
                head_fu_72 <= head_6_fu_123_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                seq_len_read_reg_173 <= seq_len;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, max_value_stream_full_n, ap_CS_fsm_state4, ap_block_state1, grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_done, ap_CS_fsm_state2, icmp_ln38_fu_129_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln38_fu_129_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((max_value_stream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_done)
    begin
        if ((grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(max_value_stream_full_n)
    begin
        if ((max_value_stream_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, seq_len_c1_full_n)
    begin
                ap_block_state1 <= ((seq_len_c1_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln38_fu_129_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln38_fu_129_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    bitcast_ln48_fu_157_p1 <= grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_val_2_out;
    grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start <= grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_ap_start_reg;
    head_6_fu_123_p2 <= std_logic_vector(unsigned(head_fu_72) + unsigned(ap_const_lv3_1));
    icmp_ln38_fu_129_p2 <= "1" when (head_fu_72 = ap_const_lv3_4) else "0";
    in_stream_TREADY <= regslice_both_in_stream_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_in_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_stream_TREADY_int_regslice <= grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln38_fu_129_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln38_fu_129_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    max_bypass_stream_din <= grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_din;
    max_bypass_stream_write <= grp_Loop_max_value_proc_Pipeline_VITIS_LOOP_41_1_fu_101_max_bypass_stream_write;

    max_value_stream_blk_n_assign_proc : process(max_value_stream_full_n, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            max_value_stream_blk_n <= max_value_stream_full_n;
        else 
            max_value_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    max_value_stream_din <= bitcast_ln48_fu_157_p1;
    max_value_stream_write <= max_value_stream_write_local;

    max_value_stream_write_local_assign_proc : process(max_value_stream_full_n, ap_CS_fsm_state4)
    begin
        if (((max_value_stream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            max_value_stream_write_local <= ap_const_logic_1;
        else 
            max_value_stream_write_local <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    seq_len_c1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, seq_len_c1_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            seq_len_c1_blk_n <= seq_len_c1_full_n;
        else 
            seq_len_c1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    seq_len_c1_din <= seq_len;
    seq_len_c1_write <= seq_len_c1_write_local;

    seq_len_c1_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            seq_len_c1_write_local <= ap_const_logic_1;
        else 
            seq_len_c1_write_local <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
