-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Gemv_Test_Stream_Copy is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    rows : IN STD_LOGIC_VECTOR (31 downto 0);
    cols : IN STD_LOGIC_VECTOR (31 downto 0);
    input_buffer : IN STD_LOGIC_VECTOR (15 downto 0);
    dispacher_0_din : OUT STD_LOGIC_VECTOR (2047 downto 0);
    dispacher_0_full_n : IN STD_LOGIC;
    dispacher_0_write : OUT STD_LOGIC;
    dispacher_0_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    dispacher_0_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    dispacher_1_din : OUT STD_LOGIC_VECTOR (2047 downto 0);
    dispacher_1_full_n : IN STD_LOGIC;
    dispacher_1_write : OUT STD_LOGIC;
    dispacher_1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    dispacher_1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    dispacher_2_din : OUT STD_LOGIC_VECTOR (2047 downto 0);
    dispacher_2_full_n : IN STD_LOGIC;
    dispacher_2_write : OUT STD_LOGIC;
    dispacher_2_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    dispacher_2_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    dispacher_3_din : OUT STD_LOGIC_VECTOR (2047 downto 0);
    dispacher_3_full_n : IN STD_LOGIC;
    dispacher_3_write : OUT STD_LOGIC;
    dispacher_3_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    dispacher_3_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of Gemv_Test_Stream_Copy is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal cols_1_fu_181_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal cols_1_reg_237 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal smax_fu_199_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal smax_reg_242 : STD_LOGIC_VECTOR (28 downto 0);
    signal smax3_fu_213_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal smax3_reg_247 : STD_LOGIC_VECTOR (23 downto 0);
    signal bound_fu_84_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal bound_reg_252 : STD_LOGIC_VECTOR (52 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_start : STD_LOGIC;
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_done : STD_LOGIC;
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_idle : STD_LOGIC;
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_ready : STD_LOGIC;
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_0_din : STD_LOGIC_VECTOR (2047 downto 0);
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_0_write : STD_LOGIC;
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_1_din : STD_LOGIC_VECTOR (2047 downto 0);
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_1_write : STD_LOGIC;
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_2_din : STD_LOGIC_VECTOR (2047 downto 0);
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_2_write : STD_LOGIC;
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_3_din : STD_LOGIC_VECTOR (2047 downto 0);
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_3_write : STD_LOGIC;
    signal grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal bound_fu_84_p0 : STD_LOGIC_VECTOR (28 downto 0);
    signal bound_fu_84_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sub_ln73_fu_97_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_103_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_8_fu_89_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln73_1_fu_113_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_5_fu_119_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal rows_1_fu_129_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal sub_ln73_2_fu_149_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_155_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_9_fu_141_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln73_3_fu_165_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_7_fu_171_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal empty_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln73_fu_137_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal empty_1097_fu_207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln4_fu_189_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal bound_fu_84_p00 : STD_LOGIC_VECTOR (52 downto 0);
    signal bound_fu_84_p10 : STD_LOGIC_VECTOR (52 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component Gemv_Test_Stream_Copy_Pipeline_row_loop_col_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        dispacher_0_din : OUT STD_LOGIC_VECTOR (2047 downto 0);
        dispacher_0_full_n : IN STD_LOGIC;
        dispacher_0_write : OUT STD_LOGIC;
        dispacher_0_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        dispacher_0_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        dispacher_1_din : OUT STD_LOGIC_VECTOR (2047 downto 0);
        dispacher_1_full_n : IN STD_LOGIC;
        dispacher_1_write : OUT STD_LOGIC;
        dispacher_1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        dispacher_1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        dispacher_2_din : OUT STD_LOGIC_VECTOR (2047 downto 0);
        dispacher_2_full_n : IN STD_LOGIC;
        dispacher_2_write : OUT STD_LOGIC;
        dispacher_2_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        dispacher_2_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        dispacher_3_din : OUT STD_LOGIC_VECTOR (2047 downto 0);
        dispacher_3_full_n : IN STD_LOGIC;
        dispacher_3_write : OUT STD_LOGIC;
        dispacher_3_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        dispacher_3_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        bound : IN STD_LOGIC_VECTOR (52 downto 0);
        input_buffer : IN STD_LOGIC_VECTOR (15 downto 0);
        cols_1 : IN STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component Gemv_Test_mul_29ns_24ns_53_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (28 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (52 downto 0) );
    end component;



begin
    grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68 : component Gemv_Test_Stream_Copy_Pipeline_row_loop_col_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_start,
        ap_done => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_done,
        ap_idle => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_idle,
        ap_ready => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_ready,
        dispacher_0_din => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_0_din,
        dispacher_0_full_n => dispacher_0_full_n,
        dispacher_0_write => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_0_write,
        dispacher_0_num_data_valid => dispacher_0_num_data_valid,
        dispacher_0_fifo_cap => dispacher_0_fifo_cap,
        dispacher_1_din => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_1_din,
        dispacher_1_full_n => dispacher_1_full_n,
        dispacher_1_write => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_1_write,
        dispacher_1_num_data_valid => dispacher_1_num_data_valid,
        dispacher_1_fifo_cap => dispacher_1_fifo_cap,
        dispacher_2_din => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_2_din,
        dispacher_2_full_n => dispacher_2_full_n,
        dispacher_2_write => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_2_write,
        dispacher_2_num_data_valid => dispacher_2_num_data_valid,
        dispacher_2_fifo_cap => dispacher_2_fifo_cap,
        dispacher_3_din => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_3_din,
        dispacher_3_full_n => dispacher_3_full_n,
        dispacher_3_write => grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_3_write,
        dispacher_3_num_data_valid => dispacher_3_num_data_valid,
        dispacher_3_fifo_cap => dispacher_3_fifo_cap,
        bound => bound_reg_252,
        input_buffer => input_buffer,
        cols_1 => cols_1_reg_237);

    mul_29ns_24ns_53_1_1_U87 : component Gemv_Test_mul_29ns_24ns_53_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 29,
        din1_WIDTH => 24,
        dout_WIDTH => 53)
    port map (
        din0 => bound_fu_84_p0,
        din1 => bound_fu_84_p1,
        dout => bound_fu_84_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_ready = ap_const_logic_1)) then 
                    grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                bound_reg_252 <= bound_fu_84_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                cols_1_reg_237 <= cols_1_fu_181_p3;
                smax3_reg_247 <= smax3_fu_213_p3;
                smax_reg_242 <= smax_fu_199_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_done)
    begin
        if ((grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    bound_fu_84_p0 <= bound_fu_84_p00(29 - 1 downto 0);
    bound_fu_84_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax_reg_242),53));
    bound_fu_84_p1 <= bound_fu_84_p10(24 - 1 downto 0);
    bound_fu_84_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax3_reg_247),53));
    cols_1_fu_181_p3 <= 
        sub_ln73_3_fu_165_p2 when (tmp_9_fu_141_p3(0) = '1') else 
        tmp_7_fu_171_p4;
    dispacher_0_din <= grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_0_din;
    dispacher_0_write <= grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_0_write;
    dispacher_1_din <= grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_1_din;
    dispacher_1_write <= grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_1_write;
    dispacher_2_din <= grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_2_din;
    dispacher_2_write <= grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_2_write;
    dispacher_3_din <= grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_3_din;
    dispacher_3_write <= grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_dispacher_3_write;
    empty_1097_fu_207_p2 <= "1" when (signed(cols_1_fu_181_p3) > signed(ap_const_lv25_0)) else "0";
    empty_fu_193_p2 <= "1" when (signed(rows_1_fu_129_p3) > signed(ap_const_lv30_0)) else "0";
    grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_start <= grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_start_reg;

    internal_ap_ready_assign_proc : process(grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_Stream_Copy_Pipeline_row_loop_col_loop_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    rows_1_fu_129_p3 <= 
        sub_ln73_1_fu_113_p2 when (tmp_8_fu_89_p3(0) = '1') else 
        tmp_5_fu_119_p4;
    smax3_fu_213_p3 <= 
        trunc_ln4_fu_189_p1 when (empty_1097_fu_207_p2(0) = '1') else 
        ap_const_lv24_0;
    smax_fu_199_p3 <= 
        trunc_ln73_fu_137_p1 when (empty_fu_193_p2(0) = '1') else 
        ap_const_lv29_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln73_1_fu_113_p2 <= std_logic_vector(unsigned(ap_const_lv30_0) - unsigned(tmp_fu_103_p4));
    sub_ln73_2_fu_149_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(cols));
    sub_ln73_3_fu_165_p2 <= std_logic_vector(unsigned(ap_const_lv25_0) - unsigned(tmp_6_fu_155_p4));
    sub_ln73_fu_97_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(rows));
    tmp_5_fu_119_p4 <= rows(31 downto 2);
    tmp_6_fu_155_p4 <= sub_ln73_2_fu_149_p2(31 downto 7);
    tmp_7_fu_171_p4 <= cols(31 downto 7);
    tmp_8_fu_89_p3 <= rows(31 downto 31);
    tmp_9_fu_141_p3 <= cols(31 downto 31);
    tmp_fu_103_p4 <= sub_ln73_fu_97_p2(31 downto 2);
    trunc_ln4_fu_189_p1 <= cols_1_fu_181_p3(24 - 1 downto 0);
    trunc_ln73_fu_137_p1 <= rows_1_fu_129_p3(29 - 1 downto 0);
end behav;
