-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Gemv_Test_Mul_Adder_Tree_128_Loop_adder_2_1_proc_8_Pipeline_adder_2_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pass_2_i_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    pass_2_i_empty_n : IN STD_LOGIC;
    pass_2_i_read : OUT STD_LOGIC;
    pass_2_i_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    pass_2_i_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    adder_tree_output_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    adder_tree_output_0_full_n : IN STD_LOGIC;
    adder_tree_output_0_write : OUT STD_LOGIC;
    adder_tree_output_0_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    adder_tree_output_0_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    select_ln59 : IN STD_LOGIC_VECTOR (22 downto 0) );
end;


architecture behav of Gemv_Test_Mul_Adder_Tree_128_Loop_adder_2_1_proc_8_Pipeline_adder_2_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv22_1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_10 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_const_lv12_FF0 : STD_LOGIC_VECTOR (11 downto 0) := "111111110000";
    constant ap_const_lv11_10 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_const_lv12_36 : STD_LOGIC_VECTOR (11 downto 0) := "000000110110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_2F : STD_LOGIC_VECTOR (5 downto 0) := "101111";
    constant ap_const_lv10_201 : STD_LOGIC_VECTOR (9 downto 0) := "1000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_36 : STD_LOGIC_VECTOR (10 downto 0) := "00000110110";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv12_11 : STD_LOGIC_VECTOR (11 downto 0) := "000000010001";
    constant ap_const_lv54_3FFFFFFFFFFFFF : STD_LOGIC_VECTOR (53 downto 0) := "111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv32_7FFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "01111111111111111111111111111111";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln182_fu_177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal pass_2_i_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal adder_tree_output_0_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln185_fu_196_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln185_reg_974 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal trunc_ln185_1_reg_979 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_238_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_994 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_994_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln195_fu_280_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln195_reg_1003 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln195_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_reg_1010 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_reg_1010_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln195_1_fu_294_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln195_1_reg_1016 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln195_1_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_1_reg_1022 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln195_1_fu_330_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln195_1_reg_1027 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln195_13_fu_338_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln195_13_reg_1034 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln195_4_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_4_reg_1040 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_17_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_17_reg_1045 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_548_fu_370_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_548_reg_1050 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_18_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_18_reg_1055 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_18_reg_1055_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_7_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_7_reg_1060 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_7_reg_1060_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_553_reg_1067 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_553_reg_1067_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lD_0_i_i_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lD_0_i_i_reg_1074 : STD_LOGIC_VECTOR (0 downto 0);
    signal ref_tmp_i_i_0_i_fu_564_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal ref_tmp_i_i_0_i_reg_1081 : STD_LOGIC_VECTOR (31 downto 0);
    signal carry_1_i_i_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_1_i_i_reg_1086 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_552_reg_1093 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_1_i_i_fu_664_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_1_i_i_reg_1100 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_1_fu_683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_1_reg_1105 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_i_i_fu_742_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_i_i_reg_1110 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_i_i_fu_761_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_i_i_reg_1117 : STD_LOGIC_VECTOR (0 downto 0);
    signal iter_fu_134 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    signal add_ln182_fu_183_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_iter_load : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal pass_2_i_read_local : STD_LOGIC;
    signal ref_tmp_i_i_4_i_fu_939_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal adder_tree_output_0_write_local : STD_LOGIC;
    signal grp_fu_157_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_157_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_157_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal iter_cast_fu_173_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal pf_fu_161_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln735_fu_230_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_fu_246_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln195_9_fu_258_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln195_1_cast_fu_262_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln195_6_fu_270_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal sub_ln195_fu_274_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal trunc_ln195_fu_234_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln195_fu_254_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln195_fu_314_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln195_11_fu_304_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln195_12_fu_320_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln195_2_fu_324_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_547_fu_348_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln195_10_fu_300_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_548_fu_370_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln195_4_fu_378_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln195_fu_386_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln195_3_fu_390_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_551_fu_396_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln195_4_fu_412_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tobool130_i_i_fu_442_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln195_9_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool130_i_i_fu_442_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln195_2_fu_476_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln195_fu_479_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln195_3_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln195_14_fu_484_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln195_7_fu_469_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln195_4_fu_456_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln195_fu_496_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln195_2_fu_488_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal cond63_i_i_fu_508_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln195_3_fu_521_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln195_2_fu_525_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_550_fu_531_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_2_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_2_fu_545_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_9_fu_551_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ref_tmp_i_i_0_i_fu_564_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal ref_tmp_i_i_0_i_fu_564_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal ref_tmp_i_i_0_i_fu_564_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_549_fu_513_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_10_fu_583_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_fu_539_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln195_5_fu_595_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln195_16_fu_625_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln195_5_fu_629_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal lshr_ln195_fu_633_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal lshr_ln195_1_fu_638_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_554_fu_650_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_11_fu_619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_12_fu_644_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_12_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_10_fu_613_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_11_fu_608_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_14_fu_688_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_16_fu_706_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_13_fu_717_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_15_fu_700_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln195_5_fu_723_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_1_fu_672_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_11_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_i_i_fu_742_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_i_i_fu_742_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_734_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_zeros_2_i_i_fu_761_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_i_i_fu_761_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_i_i_fu_761_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln195_1_fu_790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_4_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_5_fu_805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond189_i_i_fu_799_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_icmp_ln195_735_fu_815_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_12_fu_826_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_0_i_i_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_0_i_i_fu_838_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_0_i_i_fu_838_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_0_i_i_fu_838_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln195_4_fu_785_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_5_fu_858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_13_fu_864_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln195_2_fu_869_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_6_fu_874_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_0_i_i_fu_820_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_7_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_0_i_i_fu_838_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_7_fu_890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_8_fu_896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_6_fu_879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln195_3_fu_902_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_8_fu_916_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_14_fu_921_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln195_15_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ref_tmp_i_i_4_i_fu_939_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ref_tmp_i_i_4_i_fu_939_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal ref_tmp_i_i_4_i_fu_939_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_157_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_548_fu_370_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool130_i_i_fu_442_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ref_tmp_i_i_0_i_fu_564_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_i_i_0_i_fu_564_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_i_i_0_i_fu_564_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_ones_2_i_i_fu_742_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_ones_2_i_i_fu_742_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_ones_2_i_i_fu_742_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_zeros_2_i_i_fu_761_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_zeros_2_i_i_fu_761_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_zeros_2_i_i_fu_761_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal neg_src_0_i_i_fu_838_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal neg_src_0_i_i_fu_838_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal neg_src_0_i_i_fu_838_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_i_i_4_i_fu_939_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_i_i_4_i_fu_939_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_i_i_4_i_fu_939_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component Gemv_Test_hptodp_16ns_64_1_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component Gemv_Test_bitselect_1ns_54ns_6ns_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (53 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component Gemv_Test_sparsemux_7_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Gemv_Test_sparsemux_7_2_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component Gemv_Test_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    hadd_16ns_16ns_16_3_no_dsp_1_U661 : component Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_157_p0,
        din1 => grp_fu_157_p1,
        ce => grp_fu_157_ce,
        dout => grp_fu_157_p2);

    hptodp_16ns_64_1_no_dsp_1_U662 : component Gemv_Test_hptodp_16ns_64_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        dout_WIDTH => 64)
    port map (
        din0 => grp_fu_157_p2,
        dout => pf_fu_161_p1);

    bitselect_1ns_54ns_6ns_1_1_1_U663 : component Gemv_Test_bitselect_1ns_54ns_6ns_1_1_1
    generic map (
        DATAWIDTH => 54,
        ADDRWIDTH => 6)
    port map (
        din => select_ln195_fu_280_p3,
        sel => tmp_548_fu_370_p2,
        dout => tmp_548_fu_370_p3);

    bitselect_1ns_54ns_6ns_1_1_1_U664 : component Gemv_Test_bitselect_1ns_54ns_6ns_1_1_1
    generic map (
        DATAWIDTH => 54,
        ADDRWIDTH => 6)
    port map (
        din => select_ln195_fu_280_p3,
        sel => tobool130_i_i_fu_442_p2,
        dout => tobool130_i_i_fu_442_p3);

    sparsemux_7_2_32_1_1_U665 : component Gemv_Test_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "00",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => trunc_ln195_13_reg_1034,
        din1 => add_ln195_2_fu_525_p2,
        din2 => ref_tmp_i_i_0_i_fu_564_p6,
        def => ref_tmp_i_i_0_i_fu_564_p7,
        sel => ref_tmp_i_i_0_i_fu_564_p8,
        dout => ref_tmp_i_i_0_i_fu_564_p9);

    sparsemux_7_2_1_1_1_U666 : component Gemv_Test_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "00",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => Range1_all_ones_2_i_i_fu_742_p2,
        din1 => lD_0_i_i_reg_1074,
        din2 => xor_ln195_11_fu_608_p2,
        def => Range1_all_ones_2_i_i_fu_742_p7,
        sel => sel_tmp_fu_734_p3,
        dout => Range1_all_ones_2_i_i_fu_742_p9);

    sparsemux_7_2_1_1_1_U667 : component Gemv_Test_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "00",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => Range1_all_zeros_2_i_i_fu_761_p2,
        din1 => xor_ln195_1_fu_683_p2,
        din2 => Range1_all_zeros_2_i_i_fu_761_p6,
        def => Range1_all_zeros_2_i_i_fu_761_p7,
        sel => sel_tmp_fu_734_p3,
        dout => Range1_all_zeros_2_i_i_fu_761_p9);

    sparsemux_7_2_1_1_1_U668 : component Gemv_Test_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "00",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => neg_src_0_i_i_fu_838_p2,
        din1 => neg_src_0_i_i_fu_838_p4,
        din2 => ap_const_lv1_0,
        def => neg_src_0_i_i_fu_838_p7,
        sel => neg_src_0_i_i_fu_838_p8,
        dout => neg_src_0_i_i_fu_838_p9);

    sparsemux_7_2_32_1_1_U669 : component Gemv_Test_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "00",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_0,
        din1 => ref_tmp_i_i_4_i_fu_939_p4,
        din2 => ref_tmp_i_i_0_i_reg_1081,
        def => ref_tmp_i_i_4_i_fu_939_p7,
        sel => ref_tmp_i_i_4_i_fu_939_p8,
        dout => ref_tmp_i_i_4_i_fu_939_p9);

    flow_control_loop_pipe_sequential_init_U : component Gemv_Test_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    iter_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln182_fu_177_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    iter_fu_134 <= add_ln182_fu_183_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    iter_fu_134 <= ap_const_lv22_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                Range1_all_ones_2_i_i_reg_1110 <= Range1_all_ones_2_i_i_fu_742_p9;
                Range1_all_zeros_2_i_i_reg_1117 <= Range1_all_zeros_2_i_i_fu_761_p9;
                Range2_all_ones_1_i_i_reg_1100 <= Range2_all_ones_1_i_i_fu_664_p3;
                carry_1_i_i_reg_1086 <= carry_1_i_i_fu_589_p2;
                icmp_ln195_17_reg_1045 <= icmp_ln195_17_fu_358_p2;
                icmp_ln195_18_reg_1055 <= icmp_ln195_18_fu_406_p2;
                icmp_ln195_18_reg_1055_pp0_iter5_reg <= icmp_ln195_18_reg_1055;
                icmp_ln195_1_reg_1022 <= icmp_ln195_1_fu_308_p2;
                icmp_ln195_4_reg_1040 <= icmp_ln195_4_fu_342_p2;
                icmp_ln195_7_reg_1060 <= icmp_ln195_7_fu_422_p2;
                icmp_ln195_7_reg_1060_pp0_iter5_reg <= icmp_ln195_7_reg_1060;
                icmp_ln195_reg_1010 <= icmp_ln195_fu_288_p2;
                icmp_ln195_reg_1010_pp0_iter5_reg <= icmp_ln195_reg_1010;
                lD_0_i_i_reg_1074 <= lD_0_i_i_fu_450_p2;
                ref_tmp_i_i_0_i_reg_1081 <= ref_tmp_i_i_0_i_fu_564_p9;
                select_ln195_1_reg_1027 <= select_ln195_1_fu_330_p3;
                select_ln195_reg_1003 <= select_ln195_fu_280_p3;
                sub_ln195_1_reg_1016 <= sub_ln195_1_fu_294_p2;
                tmp_548_reg_1050 <= tmp_548_fu_370_p3;
                tmp_552_reg_1093 <= ref_tmp_i_i_0_i_fu_564_p9(31 downto 31);
                tmp_553_reg_1067 <= add_ln195_4_fu_412_p2(11 downto 11);
                tmp_553_reg_1067_pp0_iter5_reg <= tmp_553_reg_1067;
                tmp_reg_994 <= bitcast_ln735_fu_230_p1(63 downto 63);
                tmp_reg_994_pp0_iter5_reg <= tmp_reg_994;
                trunc_ln195_13_reg_1034 <= trunc_ln195_13_fu_338_p1;
                xor_ln195_1_reg_1105 <= xor_ln195_1_fu_683_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln185_1_reg_979 <= pass_2_i_dout(31 downto 16);
                trunc_ln185_reg_974 <= trunc_ln185_fu_196_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Range1_all_ones_2_i_i_fu_742_p2 <= (lD_0_i_i_reg_1074 and Range2_all_ones_1_i_i_fu_664_p3);
    Range1_all_ones_2_i_i_fu_742_p7 <= "X";
    Range1_all_zeros_2_i_i_fu_761_p2 <= (xor_ln195_1_fu_683_p2 and icmp_ln195_14_fu_688_p2);
    Range1_all_zeros_2_i_i_fu_761_p6 <= (xor_ln195_11_fu_608_p2 or icmp_ln195_16_fu_706_p2);
    Range1_all_zeros_2_i_i_fu_761_p7 <= "X";
    Range2_all_ones_1_i_i_fu_664_p3 <= 
        icmp_ln195_12_fu_644_p2 when (icmp_ln195_11_fu_619_p2(0) = '1') else 
        xor_ln195_12_fu_658_p2;
    add_ln182_fu_183_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_iter_load) + unsigned(ap_const_lv22_1));
    add_ln195_2_fu_525_p2 <= std_logic_vector(unsigned(select_ln195_2_fu_488_p3) + unsigned(zext_ln195_3_fu_521_p1));
    add_ln195_3_fu_390_p2 <= std_logic_vector(signed(sext_ln195_fu_386_p1) + signed(zext_ln195_fu_254_p1));
    add_ln195_4_fu_412_p2 <= std_logic_vector(unsigned(sub_ln195_1_fu_294_p2) + unsigned(ap_const_lv12_10));
    add_ln195_5_fu_595_p2 <= std_logic_vector(unsigned(sub_ln195_1_reg_1016) + unsigned(ap_const_lv12_11));
    add_ln195_fu_314_p2 <= std_logic_vector(unsigned(sub_ln195_1_fu_294_p2) + unsigned(ap_const_lv12_FF0));

    adder_tree_output_0_blk_n_assign_proc : process(ap_enable_reg_pp0_iter6, adder_tree_output_0_full_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            adder_tree_output_0_blk_n <= adder_tree_output_0_full_n;
        else 
            adder_tree_output_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    adder_tree_output_0_din <= ref_tmp_i_i_4_i_fu_939_p9;
    adder_tree_output_0_write <= adder_tree_output_0_write_local;

    adder_tree_output_0_write_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            adder_tree_output_0_write_local <= ap_const_logic_1;
        else 
            adder_tree_output_0_write_local <= ap_const_logic_0;
        end if; 
    end process;

    and_ln195_10_fu_583_p2 <= (tmp_549_fu_513_p3 and and_ln195_9_fu_551_p2);
    and_ln195_11_fu_728_p2 <= (or_ln195_5_fu_723_p2 and icmp_ln195_15_fu_700_p2);
    and_ln195_12_fu_826_p2 <= (tmp_reg_994_pp0_iter5_reg and icmp_ln195_7_reg_1060_pp0_iter5_reg);
    and_ln195_13_fu_864_p2 <= (xor_ln195_5_fu_858_p2 and icmp_ln195_7_reg_1060_pp0_iter5_reg);
    and_ln195_14_fu_921_p2 <= (xor_ln195_8_fu_916_p2 and or_ln195_3_fu_902_p2);
    and_ln195_15_fu_927_p2 <= (icmp_ln195_18_reg_1055_pp0_iter5_reg and and_ln195_14_fu_921_p2);
    and_ln195_1_fu_672_p2 <= (xor_ln195_11_fu_608_p2 and icmp_ln195_10_fu_613_p2);
    and_ln195_4_fu_794_p2 <= (or_ln195_1_fu_790_p2 and Range2_all_ones_1_i_i_reg_1100);
    and_ln195_5_fu_805_p2 <= (carry_1_i_i_reg_1086 and Range1_all_ones_2_i_i_reg_1110);
    and_ln195_6_fu_879_p2 <= (xor_ln195_6_fu_874_p2 and or_ln195_2_fu_869_p2);
    and_ln195_7_fu_885_p2 <= (tmp_552_reg_1093 and deleted_ones_0_i_i_fu_820_p2);
    and_ln195_8_fu_896_p2 <= (xor_ln195_7_fu_890_p2 and neg_src_0_i_i_fu_838_p9);
    and_ln195_9_fu_551_p2 <= (xor_ln195_2_fu_545_p2 and icmp_ln195_1_reg_1022);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, pass_2_i_empty_n, adder_tree_output_0_full_n)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_0 = adder_tree_output_0_full_n)) or ((pass_2_i_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, pass_2_i_empty_n, adder_tree_output_0_full_n)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_0 = adder_tree_output_0_full_n)) or ((pass_2_i_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, pass_2_i_empty_n, adder_tree_output_0_full_n)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_0 = adder_tree_output_0_full_n)) or ((pass_2_i_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, pass_2_i_empty_n, adder_tree_output_0_full_n)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_0 = adder_tree_output_0_full_n)) or ((pass_2_i_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln182_fu_177_p2)
    begin
        if (((icmp_ln182_fu_177_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_iter_load_assign_proc : process(ap_CS_fsm_pp0_stage0, iter_fu_134, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_iter_load <= ap_const_lv22_0;
        else 
            ap_sig_allocacmp_iter_load <= iter_fu_134;
        end if; 
    end process;

    ashr_ln195_fu_479_p2 <= std_logic_vector(shift_right(signed(select_ln195_reg_1003),to_integer(unsigned('0' & zext_ln195_2_fu_476_p1(31-1 downto 0)))));
    bitcast_ln735_fu_230_p1 <= pf_fu_161_p1;
    carry_1_i_i_fu_589_p2 <= (xor_ln195_fu_539_p2 and and_ln195_10_fu_583_p2);
    cond189_i_i_fu_799_p3 <= 
        and_ln195_4_fu_794_p2 when (carry_1_i_i_reg_1086(0) = '1') else 
        Range1_all_ones_2_i_i_reg_1110;
    cond63_i_i_fu_508_p3 <= 
        tmp_reg_994 when (icmp_ln195_4_reg_1040(0) = '1') else 
        tmp_548_reg_1050;
    deleted_ones_0_i_i_fu_820_p2 <= (not_icmp_ln195_735_fu_815_p2 or cond189_i_i_fu_799_p3);

    grp_fu_157_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_157_ce <= ap_const_logic_1;
        else 
            grp_fu_157_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_157_p0 <= trunc_ln185_reg_974;
    grp_fu_157_p1 <= trunc_ln185_1_reg_979;
    icmp_ln182_fu_177_p2 <= "1" when (signed(iter_cast_fu_173_p1) < signed(select_ln59)) else "0";
    icmp_ln195_10_fu_613_p2 <= "1" when (signed(add_ln195_5_fu_595_p2) < signed(ap_const_lv12_36)) else "0";
    icmp_ln195_11_fu_619_p2 <= "1" when (unsigned(add_ln195_5_fu_595_p2) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln195_12_fu_644_p2 <= "1" when (lshr_ln195_fu_633_p2 = lshr_ln195_1_fu_638_p2) else "0";
    icmp_ln195_14_fu_688_p2 <= "1" when (lshr_ln195_fu_633_p2 = ap_const_lv54_0) else "0";
    icmp_ln195_15_fu_700_p2 <= "1" when (add_ln195_5_fu_595_p2 = ap_const_lv12_36) else "0";
    icmp_ln195_16_fu_706_p2 <= "1" when (select_ln195_reg_1003 = ap_const_lv54_0) else "0";
    icmp_ln195_17_fu_358_p2 <= "1" when (tmp_547_fu_348_p4 = ap_const_lv6_0) else "0";
    icmp_ln195_18_fu_406_p2 <= "1" when (signed(tmp_551_fu_396_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln195_1_fu_308_p2 <= "1" when (signed(sub_ln195_1_fu_294_p2) > signed(ap_const_lv12_10)) else "0";
    icmp_ln195_2_fu_459_p2 <= "1" when (sub_ln195_1_reg_1016 = ap_const_lv12_10) else "0";
    icmp_ln195_3_fu_464_p2 <= "1" when (unsigned(select_ln195_1_reg_1027) < unsigned(ap_const_lv11_36)) else "0";
    icmp_ln195_4_fu_342_p2 <= "1" when (signed(add_ln195_fu_314_p2) > signed(ap_const_lv12_36)) else "0";
    icmp_ln195_7_fu_422_p2 <= "1" when (signed(add_ln195_4_fu_412_p2) < signed(ap_const_lv12_36)) else "0";
    icmp_ln195_9_fu_436_p2 <= "1" when (unsigned(add_ln195_4_fu_412_p2) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln195_fu_288_p2 <= "1" when (trunc_ln195_fu_234_p1 = ap_const_lv63_0) else "0";
    iter_cast_fu_173_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_iter_load),23));
    lD_0_i_i_fu_450_p2 <= (tobool130_i_i_fu_442_p3 and icmp_ln195_9_fu_436_p2);
    lshr_ln195_1_fu_638_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv54_3FFFFFFFFFFFFF),to_integer(unsigned('0' & zext_ln195_5_fu_629_p1(31-1 downto 0)))));
    lshr_ln195_fu_633_p2 <= std_logic_vector(shift_right(unsigned(select_ln195_reg_1003),to_integer(unsigned('0' & zext_ln195_5_fu_629_p1(31-1 downto 0)))));
    neg_src_0_i_i_fu_838_p2 <= (tmp_reg_994_pp0_iter5_reg and tmp_552_reg_1093);
    neg_src_0_i_i_fu_838_p4 <= (ap_const_lv1_1 xor and_ln195_5_fu_805_p2);
    neg_src_0_i_i_fu_838_p7 <= "X";
    neg_src_0_i_i_fu_838_p8 <= (not_icmp_ln195_735_fu_815_p2 & and_ln195_12_fu_826_p2);
    not_icmp_ln195_735_fu_815_p2 <= (icmp_ln195_7_reg_1060_pp0_iter5_reg xor ap_const_lv1_1);
    or_ln195_1_fu_790_p2 <= (xor_ln195_1_reg_1105 or tmp_553_reg_1067_pp0_iter5_reg);
    or_ln195_2_fu_869_p2 <= (tmp_552_reg_1093 or and_ln195_13_fu_864_p2);
    or_ln195_3_fu_902_p2 <= (and_ln195_8_fu_896_p2 or and_ln195_6_fu_879_p2);
    or_ln195_4_fu_378_p3 <= (ap_const_lv10_201 & icmp_ln195_1_fu_308_p2);
    or_ln195_5_fu_723_p2 <= (xor_ln195_13_fu_717_p2 or tmp_553_reg_1067);

    pass_2_i_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pass_2_i_empty_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pass_2_i_blk_n <= pass_2_i_empty_n;
        else 
            pass_2_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pass_2_i_read <= pass_2_i_read_local;

    pass_2_i_read_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pass_2_i_read_local <= ap_const_logic_1;
        else 
            pass_2_i_read_local <= ap_const_logic_0;
        end if; 
    end process;

    ref_tmp_i_i_0_i_fu_564_p6 <= 
        shl_ln195_fu_496_p2 when (icmp_ln195_17_reg_1045(0) = '1') else 
        ap_const_lv32_0;
    ref_tmp_i_i_0_i_fu_564_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ref_tmp_i_i_0_i_fu_564_p8 <= (icmp_ln195_2_fu_459_p2 & and_ln195_9_fu_551_p2);
    ref_tmp_i_i_4_i_fu_939_p4 <= 
        ap_const_lv32_7FFFFFFF when (and_ln195_6_fu_879_p2(0) = '1') else 
        ap_const_lv32_80000000;
    ref_tmp_i_i_4_i_fu_939_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ref_tmp_i_i_4_i_fu_939_p8 <= (icmp_ln195_reg_1010_pp0_iter5_reg & and_ln195_15_fu_927_p2);
    sel_tmp_fu_734_p3 <= (and_ln195_1_fu_672_p2 & and_ln195_11_fu_728_p2);
    select_ln195_1_fu_330_p3 <= 
        trunc_ln195_12_fu_320_p1 when (icmp_ln195_1_fu_308_p2(0) = '1') else 
        sub_ln195_2_fu_324_p2;
    select_ln195_2_fu_488_p3 <= 
        trunc_ln195_14_fu_484_p1 when (icmp_ln195_3_fu_464_p2(0) = '1') else 
        select_ln195_7_fu_469_p3;
    select_ln195_4_fu_785_p3 <= 
        Range1_all_ones_2_i_i_reg_1110 when (carry_1_i_i_reg_1086(0) = '1') else 
        Range1_all_zeros_2_i_i_reg_1117;
    select_ln195_7_fu_469_p3 <= 
        ap_const_lv32_FFFFFFFF when (tmp_reg_994(0) = '1') else 
        ap_const_lv32_0;
    select_ln195_fu_280_p3 <= 
        sub_ln195_fu_274_p2 when (tmp_fu_238_p3(0) = '1') else 
        zext_ln195_6_fu_270_p1;
        sext_ln195_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln195_4_fu_378_p3),12));

    shl_ln195_fu_496_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln195_13_reg_1034),to_integer(unsigned('0' & zext_ln195_4_fu_456_p1(31-1 downto 0)))));
    sub_ln195_1_fu_294_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln195_fu_254_p1));
    sub_ln195_2_fu_324_p2 <= std_logic_vector(unsigned(ap_const_lv11_10) - unsigned(trunc_ln195_11_fu_304_p1));
    sub_ln195_fu_274_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln195_6_fu_270_p1));
    tmp_1_fu_246_p3 <= bitcast_ln735_fu_230_p1(62 downto 52);
    tmp_547_fu_348_p4 <= select_ln195_1_fu_330_p3(10 downto 5);
    tmp_548_fu_370_p2 <= std_logic_vector(unsigned(trunc_ln195_10_fu_300_p1) + unsigned(ap_const_lv6_2F));
    tmp_549_fu_513_p3 <= select_ln195_2_fu_488_p3(31 downto 31);
    tmp_550_fu_531_p3 <= add_ln195_2_fu_525_p2(31 downto 31);
    tmp_551_fu_396_p4 <= add_ln195_3_fu_390_p2(11 downto 4);
    tmp_554_fu_650_p3 <= add_ln195_5_fu_595_p2(11 downto 11);
    tmp_fu_238_p3 <= bitcast_ln735_fu_230_p1(63 downto 63);
    tobool130_i_i_fu_442_p2 <= add_ln195_4_fu_412_p2(6 - 1 downto 0);
    trunc_ln185_fu_196_p1 <= pass_2_i_dout(16 - 1 downto 0);
    trunc_ln195_10_fu_300_p1 <= sub_ln195_1_fu_294_p2(6 - 1 downto 0);
    trunc_ln195_11_fu_304_p1 <= sub_ln195_1_fu_294_p2(11 - 1 downto 0);
    trunc_ln195_12_fu_320_p1 <= add_ln195_fu_314_p2(11 - 1 downto 0);
    trunc_ln195_13_fu_338_p1 <= select_ln195_fu_280_p3(32 - 1 downto 0);
    trunc_ln195_14_fu_484_p1 <= ashr_ln195_fu_479_p2(32 - 1 downto 0);
    trunc_ln195_16_fu_625_p1 <= add_ln195_5_fu_595_p2(6 - 1 downto 0);
    trunc_ln195_9_fu_258_p1 <= bitcast_ln735_fu_230_p1(52 - 1 downto 0);
    trunc_ln195_fu_234_p1 <= bitcast_ln735_fu_230_p1(63 - 1 downto 0);
    xor_ln195_11_fu_608_p2 <= (tmp_553_reg_1067 xor ap_const_lv1_1);
    xor_ln195_12_fu_658_p2 <= (tmp_554_fu_650_p3 xor ap_const_lv1_1);
    xor_ln195_13_fu_717_p2 <= (icmp_ln195_10_fu_613_p2 xor ap_const_lv1_1);
    xor_ln195_1_fu_683_p2 <= (lD_0_i_i_reg_1074 xor ap_const_lv1_1);
    xor_ln195_2_fu_545_p2 <= (icmp_ln195_2_fu_459_p2 xor ap_const_lv1_1);
    xor_ln195_5_fu_858_p2 <= (select_ln195_4_fu_785_p3 xor ap_const_lv1_1);
    xor_ln195_6_fu_874_p2 <= (tmp_reg_994_pp0_iter5_reg xor ap_const_lv1_1);
    xor_ln195_7_fu_890_p2 <= (ap_const_lv1_1 xor and_ln195_7_fu_885_p2);
    xor_ln195_8_fu_916_p2 <= (icmp_ln195_reg_1010_pp0_iter5_reg xor ap_const_lv1_1);
    xor_ln195_fu_539_p2 <= (tmp_550_fu_531_p3 xor ap_const_lv1_1);
    zext_ln195_1_cast_fu_262_p3 <= (ap_const_lv1_1 & trunc_ln195_9_fu_258_p1);
    zext_ln195_2_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln195_1_reg_1027),54));
    zext_ln195_3_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cond63_i_i_fu_508_p3),32));
    zext_ln195_4_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln195_1_reg_1027),32));
    zext_ln195_5_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln195_16_fu_625_p1),54));
    zext_ln195_6_fu_270_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln195_1_cast_fu_262_p3),54));
    zext_ln195_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_246_p3),12));
end behav;
