-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Gemv_Test_Bias_Merger is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    rows_empty_n : IN STD_LOGIC;
    rows_read : OUT STD_LOGIC;
    rows_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    rows_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    dequantized_output_0_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    dequantized_output_0_empty_n : IN STD_LOGIC;
    dequantized_output_0_read : OUT STD_LOGIC;
    dequantized_output_0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dequantized_output_0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    dequantized_output_1_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    dequantized_output_1_empty_n : IN STD_LOGIC;
    dequantized_output_1_read : OUT STD_LOGIC;
    dequantized_output_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dequantized_output_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    dequantized_output_2_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    dequantized_output_2_empty_n : IN STD_LOGIC;
    dequantized_output_2_read : OUT STD_LOGIC;
    dequantized_output_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dequantized_output_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    dequantized_output_3_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    dequantized_output_3_empty_n : IN STD_LOGIC;
    dequantized_output_3_read : OUT STD_LOGIC;
    dequantized_output_3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dequantized_output_3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    out_stream_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    out_stream_full_n : IN STD_LOGIC;
    out_stream_write : OUT STD_LOGIC;
    bias_buffer_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    bias_buffer_empty_n : IN STD_LOGIC;
    bias_buffer_read : OUT STD_LOGIC;
    bias_buffer_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    bias_buffer_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of Gemv_Test_Bias_Merger is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal rows_blk_n : STD_LOGIC;
    signal bias_buffer_blk_n : STD_LOGIC;
    signal bias_buffer_read_reg_140 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal rows_2_fu_128_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal rows_2_reg_145 : STD_LOGIC_VECTOR (29 downto 0);
    signal bias_fu_136_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal bias_reg_150 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_start : STD_LOGIC;
    signal grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_done : STD_LOGIC;
    signal grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_idle : STD_LOGIC;
    signal grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_ready : STD_LOGIC;
    signal grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_0_read : STD_LOGIC;
    signal grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_1_read : STD_LOGIC;
    signal grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_2_read : STD_LOGIC;
    signal grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_3_read : STD_LOGIC;
    signal grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_out_stream_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_out_stream_write : STD_LOGIC;
    signal grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal rows_read_local : STD_LOGIC;
    signal bias_buffer_read_local : STD_LOGIC;
    signal sub_ln73_fu_96_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_102_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_583_fu_88_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln73_4_fu_112_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_s_fu_118_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Gemv_Test_Bias_Merger_Pipeline_VITIS_LOOP_14_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        dequantized_output_0_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        dequantized_output_0_empty_n : IN STD_LOGIC;
        dequantized_output_0_read : OUT STD_LOGIC;
        dequantized_output_0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dequantized_output_0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        dequantized_output_1_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        dequantized_output_1_empty_n : IN STD_LOGIC;
        dequantized_output_1_read : OUT STD_LOGIC;
        dequantized_output_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dequantized_output_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        dequantized_output_2_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        dequantized_output_2_empty_n : IN STD_LOGIC;
        dequantized_output_2_read : OUT STD_LOGIC;
        dequantized_output_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dequantized_output_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        dequantized_output_3_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        dequantized_output_3_empty_n : IN STD_LOGIC;
        dequantized_output_3_read : OUT STD_LOGIC;
        dequantized_output_3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dequantized_output_3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        out_stream_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_stream_full_n : IN STD_LOGIC;
        out_stream_write : OUT STD_LOGIC;
        rows_2 : IN STD_LOGIC_VECTOR (29 downto 0);
        bias : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68 : component Gemv_Test_Bias_Merger_Pipeline_VITIS_LOOP_14_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_start,
        ap_done => grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_done,
        ap_idle => grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_idle,
        ap_ready => grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_ready,
        dequantized_output_0_dout => dequantized_output_0_dout,
        dequantized_output_0_empty_n => dequantized_output_0_empty_n,
        dequantized_output_0_read => grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_0_read,
        dequantized_output_0_num_data_valid => ap_const_lv3_0,
        dequantized_output_0_fifo_cap => ap_const_lv3_0,
        dequantized_output_1_dout => dequantized_output_1_dout,
        dequantized_output_1_empty_n => dequantized_output_1_empty_n,
        dequantized_output_1_read => grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_1_read,
        dequantized_output_1_num_data_valid => ap_const_lv3_0,
        dequantized_output_1_fifo_cap => ap_const_lv3_0,
        dequantized_output_2_dout => dequantized_output_2_dout,
        dequantized_output_2_empty_n => dequantized_output_2_empty_n,
        dequantized_output_2_read => grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_2_read,
        dequantized_output_2_num_data_valid => ap_const_lv3_0,
        dequantized_output_2_fifo_cap => ap_const_lv3_0,
        dequantized_output_3_dout => dequantized_output_3_dout,
        dequantized_output_3_empty_n => dequantized_output_3_empty_n,
        dequantized_output_3_read => grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_3_read,
        dequantized_output_3_num_data_valid => ap_const_lv3_0,
        dequantized_output_3_fifo_cap => ap_const_lv3_0,
        out_stream_din => grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_out_stream_din,
        out_stream_full_n => out_stream_full_n,
        out_stream_write => grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_out_stream_write,
        rows_2 => rows_2_reg_145,
        bias => bias_reg_150);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_ready = ap_const_logic_1)) then 
                    grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                bias_buffer_read_reg_140 <= bias_buffer_dout;
                rows_2_reg_145 <= rows_2_fu_128_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                bias_reg_150 <= bias_fu_136_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_done)
    begin
        if ((grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, rows_empty_n, bias_buffer_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (bias_buffer_empty_n = ap_const_logic_0) or (rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    bias_buffer_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, bias_buffer_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bias_buffer_blk_n <= bias_buffer_empty_n;
        else 
            bias_buffer_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bias_buffer_read <= bias_buffer_read_local;

    bias_buffer_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bias_buffer_read_local <= ap_const_logic_1;
        else 
            bias_buffer_read_local <= ap_const_logic_0;
        end if; 
    end process;

    bias_fu_136_p1 <= bias_buffer_read_reg_140;
    dequantized_output_0_read <= grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_0_read;
    dequantized_output_1_read <= grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_1_read;
    dequantized_output_2_read <= grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_2_read;
    dequantized_output_3_read <= grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_dequantized_output_3_read;
    grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_start <= grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_ap_start_reg;
    out_stream_din <= grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_out_stream_din;
    out_stream_write <= grp_Bias_Merger_Pipeline_VITIS_LOOP_14_1_fu_68_out_stream_write;
    rows_2_fu_128_p3 <= 
        sub_ln73_4_fu_112_p2 when (tmp_583_fu_88_p3(0) = '1') else 
        tmp_s_fu_118_p4;

    rows_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, rows_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rows_blk_n <= rows_empty_n;
        else 
            rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rows_read <= rows_read_local;

    rows_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rows_read_local <= ap_const_logic_1;
        else 
            rows_read_local <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln73_4_fu_112_p2 <= std_logic_vector(unsigned(ap_const_lv30_0) - unsigned(tmp_fu_102_p4));
    sub_ln73_fu_96_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(rows_dout));
    tmp_583_fu_88_p3 <= rows_dout(31 downto 31);
    tmp_fu_102_p4 <= sub_ln73_fu_96_p2(31 downto 2);
    tmp_s_fu_118_p4 <= rows_dout(31 downto 2);
end behav;
