-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Softmax is
generic (
    C_S_AXI_CTRL_BUS_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CTRL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_CTRL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of Softmax is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Softmax_Softmax,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcv80-lsva4737-2MHP-e-S,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.649000,HLS_SYN_LAT=28759,HLS_SYN_TPT=16450,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1068,HLS_SYN_LUT=3743,HLS_VERSION=2025_1_1}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal seq_len : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_max_value_proc_U0_ap_start : STD_LOGIC;
    signal Loop_max_value_proc_U0_ap_done : STD_LOGIC;
    signal Loop_max_value_proc_U0_ap_continue : STD_LOGIC;
    signal Loop_max_value_proc_U0_ap_idle : STD_LOGIC;
    signal Loop_max_value_proc_U0_ap_ready : STD_LOGIC;
    signal Loop_max_value_proc_U0_start_out : STD_LOGIC;
    signal Loop_max_value_proc_U0_start_write : STD_LOGIC;
    signal Loop_max_value_proc_U0_max_value_stream_din : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_max_value_proc_U0_max_value_stream_write : STD_LOGIC;
    signal Loop_max_value_proc_U0_in_stream_TREADY : STD_LOGIC;
    signal Loop_max_value_proc_U0_max_bypass_stream_din : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_max_value_proc_U0_max_bypass_stream_write : STD_LOGIC;
    signal Loop_max_value_proc_U0_seq_len_c1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_max_value_proc_U0_seq_len_c1_write : STD_LOGIC;
    signal Loop_sub_max_proc_U0_ap_start : STD_LOGIC;
    signal Loop_sub_max_proc_U0_start_full_n : STD_LOGIC;
    signal Loop_sub_max_proc_U0_ap_done : STD_LOGIC;
    signal Loop_sub_max_proc_U0_ap_continue : STD_LOGIC;
    signal Loop_sub_max_proc_U0_ap_idle : STD_LOGIC;
    signal Loop_sub_max_proc_U0_ap_ready : STD_LOGIC;
    signal Loop_sub_max_proc_U0_start_out : STD_LOGIC;
    signal Loop_sub_max_proc_U0_start_write : STD_LOGIC;
    signal Loop_sub_max_proc_U0_max_value_stream_read : STD_LOGIC;
    signal Loop_sub_max_proc_U0_seq_len_read : STD_LOGIC;
    signal Loop_sub_max_proc_U0_sum_exp_stream_din : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_sub_max_proc_U0_sum_exp_stream_write : STD_LOGIC;
    signal Loop_sub_max_proc_U0_max_bypass_stream_read : STD_LOGIC;
    signal Loop_sub_max_proc_U0_exp_bypass_stream_din : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_sub_max_proc_U0_exp_bypass_stream_write : STD_LOGIC;
    signal Loop_sub_max_proc_U0_exp_bypass_stream_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_sub_max_proc_U0_exp_bypass_stream_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_sub_max_proc_U0_seq_len_c_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_sub_max_proc_U0_seq_len_c_write : STD_LOGIC;
    signal Loop_divide_proc_U0_ap_start : STD_LOGIC;
    signal Loop_divide_proc_U0_ap_done : STD_LOGIC;
    signal Loop_divide_proc_U0_ap_continue : STD_LOGIC;
    signal Loop_divide_proc_U0_ap_idle : STD_LOGIC;
    signal Loop_divide_proc_U0_ap_ready : STD_LOGIC;
    signal Loop_divide_proc_U0_sum_exp_stream_read : STD_LOGIC;
    signal Loop_divide_proc_U0_inv_sum_exp_stream_din : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_divide_proc_U0_inv_sum_exp_stream_write : STD_LOGIC;
    signal Loop_divide_proc_U0_inv_sum_exp_stream_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_divide_proc_U0_inv_sum_exp_stream_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_softmax_output_proc_U0_ap_start : STD_LOGIC;
    signal Loop_softmax_output_proc_U0_ap_done : STD_LOGIC;
    signal Loop_softmax_output_proc_U0_ap_continue : STD_LOGIC;
    signal Loop_softmax_output_proc_U0_ap_idle : STD_LOGIC;
    signal Loop_softmax_output_proc_U0_ap_ready : STD_LOGIC;
    signal Loop_softmax_output_proc_U0_inv_sum_exp_stream_read : STD_LOGIC;
    signal Loop_softmax_output_proc_U0_seq_len_read : STD_LOGIC;
    signal Loop_softmax_output_proc_U0_exp_bypass_stream_read : STD_LOGIC;
    signal Loop_softmax_output_proc_U0_out_stream_TDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_softmax_output_proc_U0_out_stream_TVALID : STD_LOGIC;
    signal max_value_stream_full_n : STD_LOGIC;
    signal max_value_stream_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal max_value_stream_empty_n : STD_LOGIC;
    signal max_value_stream_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal max_value_stream_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal max_bypass_stream_full_n : STD_LOGIC;
    signal max_bypass_stream_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal max_bypass_stream_empty_n : STD_LOGIC;
    signal max_bypass_stream_num_data_valid : STD_LOGIC_VECTOR (14 downto 0);
    signal max_bypass_stream_fifo_cap : STD_LOGIC_VECTOR (14 downto 0);
    signal seq_len_c1_full_n : STD_LOGIC;
    signal seq_len_c1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal seq_len_c1_empty_n : STD_LOGIC;
    signal seq_len_c1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal seq_len_c1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal sum_exp_stream_full_n : STD_LOGIC;
    signal sum_exp_stream_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_exp_stream_empty_n : STD_LOGIC;
    signal sum_exp_stream_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_exp_stream_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal exp_bypass_stream_full_n : STD_LOGIC;
    signal exp_bypass_stream_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal exp_bypass_stream_empty_n : STD_LOGIC;
    signal exp_bypass_stream_num_data_valid : STD_LOGIC_VECTOR (14 downto 0);
    signal exp_bypass_stream_fifo_cap : STD_LOGIC_VECTOR (14 downto 0);
    signal seq_len_c_full_n : STD_LOGIC;
    signal seq_len_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal seq_len_c_empty_n : STD_LOGIC;
    signal seq_len_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal seq_len_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal inv_sum_exp_stream_full_n : STD_LOGIC;
    signal inv_sum_exp_stream_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal inv_sum_exp_stream_empty_n : STD_LOGIC;
    signal inv_sum_exp_stream_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal inv_sum_exp_stream_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal start_for_Loop_sub_max_proc_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_sub_max_proc_U0_full_n : STD_LOGIC;
    signal start_for_Loop_sub_max_proc_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_sub_max_proc_U0_empty_n : STD_LOGIC;
    signal start_for_Loop_divide_proc_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_divide_proc_U0_full_n : STD_LOGIC;
    signal start_for_Loop_divide_proc_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_divide_proc_U0_empty_n : STD_LOGIC;
    signal start_for_Loop_softmax_output_proc_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_softmax_output_proc_U0_full_n : STD_LOGIC;
    signal start_for_Loop_softmax_output_proc_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_softmax_output_proc_U0_empty_n : STD_LOGIC;

    component Softmax_Loop_max_value_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        seq_len : IN STD_LOGIC_VECTOR (31 downto 0);
        max_value_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        max_value_stream_full_n : IN STD_LOGIC;
        max_value_stream_write : OUT STD_LOGIC;
        max_value_stream_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        max_value_stream_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        in_stream_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TREADY : OUT STD_LOGIC;
        max_bypass_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        max_bypass_stream_full_n : IN STD_LOGIC;
        max_bypass_stream_write : OUT STD_LOGIC;
        max_bypass_stream_num_data_valid : IN STD_LOGIC_VECTOR (14 downto 0);
        max_bypass_stream_fifo_cap : IN STD_LOGIC_VECTOR (14 downto 0);
        seq_len_c1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        seq_len_c1_full_n : IN STD_LOGIC;
        seq_len_c1_write : OUT STD_LOGIC;
        seq_len_c1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        seq_len_c1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component Softmax_Loop_sub_max_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        max_value_stream_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        max_value_stream_empty_n : IN STD_LOGIC;
        max_value_stream_read : OUT STD_LOGIC;
        max_value_stream_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        max_value_stream_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        seq_len_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        seq_len_empty_n : IN STD_LOGIC;
        seq_len_read : OUT STD_LOGIC;
        seq_len_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        seq_len_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        sum_exp_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        sum_exp_stream_full_n : IN STD_LOGIC;
        sum_exp_stream_write : OUT STD_LOGIC;
        sum_exp_stream_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        sum_exp_stream_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        max_bypass_stream_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        max_bypass_stream_empty_n : IN STD_LOGIC;
        max_bypass_stream_read : OUT STD_LOGIC;
        max_bypass_stream_num_data_valid : IN STD_LOGIC_VECTOR (14 downto 0);
        max_bypass_stream_fifo_cap : IN STD_LOGIC_VECTOR (14 downto 0);
        exp_bypass_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        exp_bypass_stream_full_n : IN STD_LOGIC;
        exp_bypass_stream_write : OUT STD_LOGIC;
        exp_bypass_stream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        exp_bypass_stream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        seq_len_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        seq_len_c_full_n : IN STD_LOGIC;
        seq_len_c_write : OUT STD_LOGIC;
        seq_len_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        seq_len_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component Softmax_Loop_divide_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sum_exp_stream_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        sum_exp_stream_empty_n : IN STD_LOGIC;
        sum_exp_stream_read : OUT STD_LOGIC;
        sum_exp_stream_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        sum_exp_stream_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        inv_sum_exp_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        inv_sum_exp_stream_full_n : IN STD_LOGIC;
        inv_sum_exp_stream_write : OUT STD_LOGIC;
        inv_sum_exp_stream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        inv_sum_exp_stream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Softmax_Loop_softmax_output_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inv_sum_exp_stream_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        inv_sum_exp_stream_empty_n : IN STD_LOGIC;
        inv_sum_exp_stream_read : OUT STD_LOGIC;
        inv_sum_exp_stream_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        inv_sum_exp_stream_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        seq_len_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        seq_len_empty_n : IN STD_LOGIC;
        seq_len_read : OUT STD_LOGIC;
        seq_len_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        seq_len_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        exp_bypass_stream_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        exp_bypass_stream_empty_n : IN STD_LOGIC;
        exp_bypass_stream_read : OUT STD_LOGIC;
        exp_bypass_stream_num_data_valid : IN STD_LOGIC_VECTOR (14 downto 0);
        exp_bypass_stream_fifo_cap : IN STD_LOGIC_VECTOR (14 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC );
    end component;


    component Softmax_fifo_w16_d128_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component Softmax_fifo_w16_d16384_U IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (14 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component Softmax_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component Softmax_fifo_w32_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component Softmax_start_for_Loop_sub_max_proc_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component Softmax_start_for_Loop_divide_proc_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component Softmax_start_for_Loop_softmax_output_proc_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component Softmax_CTRL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        seq_len : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    CTRL_BUS_s_axi_U : component Softmax_CTRL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_BUS_AWVALID,
        AWREADY => s_axi_CTRL_BUS_AWREADY,
        AWADDR => s_axi_CTRL_BUS_AWADDR,
        WVALID => s_axi_CTRL_BUS_WVALID,
        WREADY => s_axi_CTRL_BUS_WREADY,
        WDATA => s_axi_CTRL_BUS_WDATA,
        WSTRB => s_axi_CTRL_BUS_WSTRB,
        ARVALID => s_axi_CTRL_BUS_ARVALID,
        ARREADY => s_axi_CTRL_BUS_ARREADY,
        ARADDR => s_axi_CTRL_BUS_ARADDR,
        RVALID => s_axi_CTRL_BUS_RVALID,
        RREADY => s_axi_CTRL_BUS_RREADY,
        RDATA => s_axi_CTRL_BUS_RDATA,
        RRESP => s_axi_CTRL_BUS_RRESP,
        BVALID => s_axi_CTRL_BUS_BVALID,
        BREADY => s_axi_CTRL_BUS_BREADY,
        BRESP => s_axi_CTRL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        seq_len => seq_len);

    Loop_max_value_proc_U0 : component Softmax_Loop_max_value_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_max_value_proc_U0_ap_start,
        start_full_n => start_for_Loop_sub_max_proc_U0_full_n,
        ap_done => Loop_max_value_proc_U0_ap_done,
        ap_continue => Loop_max_value_proc_U0_ap_continue,
        ap_idle => Loop_max_value_proc_U0_ap_idle,
        ap_ready => Loop_max_value_proc_U0_ap_ready,
        start_out => Loop_max_value_proc_U0_start_out,
        start_write => Loop_max_value_proc_U0_start_write,
        seq_len => seq_len,
        max_value_stream_din => Loop_max_value_proc_U0_max_value_stream_din,
        max_value_stream_full_n => max_value_stream_full_n,
        max_value_stream_write => Loop_max_value_proc_U0_max_value_stream_write,
        max_value_stream_num_data_valid => max_value_stream_num_data_valid,
        max_value_stream_fifo_cap => max_value_stream_fifo_cap,
        in_stream_TDATA => in_stream_TDATA,
        in_stream_TVALID => in_stream_TVALID,
        in_stream_TREADY => Loop_max_value_proc_U0_in_stream_TREADY,
        max_bypass_stream_din => Loop_max_value_proc_U0_max_bypass_stream_din,
        max_bypass_stream_full_n => max_bypass_stream_full_n,
        max_bypass_stream_write => Loop_max_value_proc_U0_max_bypass_stream_write,
        max_bypass_stream_num_data_valid => max_bypass_stream_num_data_valid,
        max_bypass_stream_fifo_cap => max_bypass_stream_fifo_cap,
        seq_len_c1_din => Loop_max_value_proc_U0_seq_len_c1_din,
        seq_len_c1_full_n => seq_len_c1_full_n,
        seq_len_c1_write => Loop_max_value_proc_U0_seq_len_c1_write,
        seq_len_c1_num_data_valid => seq_len_c1_num_data_valid,
        seq_len_c1_fifo_cap => seq_len_c1_fifo_cap);

    Loop_sub_max_proc_U0 : component Softmax_Loop_sub_max_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_sub_max_proc_U0_ap_start,
        start_full_n => Loop_sub_max_proc_U0_start_full_n,
        ap_done => Loop_sub_max_proc_U0_ap_done,
        ap_continue => Loop_sub_max_proc_U0_ap_continue,
        ap_idle => Loop_sub_max_proc_U0_ap_idle,
        ap_ready => Loop_sub_max_proc_U0_ap_ready,
        start_out => Loop_sub_max_proc_U0_start_out,
        start_write => Loop_sub_max_proc_U0_start_write,
        max_value_stream_dout => max_value_stream_dout,
        max_value_stream_empty_n => max_value_stream_empty_n,
        max_value_stream_read => Loop_sub_max_proc_U0_max_value_stream_read,
        max_value_stream_num_data_valid => max_value_stream_num_data_valid,
        max_value_stream_fifo_cap => max_value_stream_fifo_cap,
        seq_len_dout => seq_len_c1_dout,
        seq_len_empty_n => seq_len_c1_empty_n,
        seq_len_read => Loop_sub_max_proc_U0_seq_len_read,
        seq_len_num_data_valid => seq_len_c1_num_data_valid,
        seq_len_fifo_cap => seq_len_c1_fifo_cap,
        sum_exp_stream_din => Loop_sub_max_proc_U0_sum_exp_stream_din,
        sum_exp_stream_full_n => sum_exp_stream_full_n,
        sum_exp_stream_write => Loop_sub_max_proc_U0_sum_exp_stream_write,
        sum_exp_stream_num_data_valid => sum_exp_stream_num_data_valid,
        sum_exp_stream_fifo_cap => sum_exp_stream_fifo_cap,
        max_bypass_stream_dout => max_bypass_stream_dout,
        max_bypass_stream_empty_n => max_bypass_stream_empty_n,
        max_bypass_stream_read => Loop_sub_max_proc_U0_max_bypass_stream_read,
        max_bypass_stream_num_data_valid => max_bypass_stream_num_data_valid,
        max_bypass_stream_fifo_cap => max_bypass_stream_fifo_cap,
        exp_bypass_stream_din => Loop_sub_max_proc_U0_exp_bypass_stream_din,
        exp_bypass_stream_full_n => exp_bypass_stream_full_n,
        exp_bypass_stream_write => Loop_sub_max_proc_U0_exp_bypass_stream_write,
        exp_bypass_stream_num_data_valid => Loop_sub_max_proc_U0_exp_bypass_stream_num_data_valid,
        exp_bypass_stream_fifo_cap => Loop_sub_max_proc_U0_exp_bypass_stream_fifo_cap,
        seq_len_c_din => Loop_sub_max_proc_U0_seq_len_c_din,
        seq_len_c_full_n => seq_len_c_full_n,
        seq_len_c_write => Loop_sub_max_proc_U0_seq_len_c_write,
        seq_len_c_num_data_valid => seq_len_c_num_data_valid,
        seq_len_c_fifo_cap => seq_len_c_fifo_cap);

    Loop_divide_proc_U0 : component Softmax_Loop_divide_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_divide_proc_U0_ap_start,
        ap_done => Loop_divide_proc_U0_ap_done,
        ap_continue => Loop_divide_proc_U0_ap_continue,
        ap_idle => Loop_divide_proc_U0_ap_idle,
        ap_ready => Loop_divide_proc_U0_ap_ready,
        sum_exp_stream_dout => sum_exp_stream_dout,
        sum_exp_stream_empty_n => sum_exp_stream_empty_n,
        sum_exp_stream_read => Loop_divide_proc_U0_sum_exp_stream_read,
        sum_exp_stream_num_data_valid => sum_exp_stream_num_data_valid,
        sum_exp_stream_fifo_cap => sum_exp_stream_fifo_cap,
        inv_sum_exp_stream_din => Loop_divide_proc_U0_inv_sum_exp_stream_din,
        inv_sum_exp_stream_full_n => inv_sum_exp_stream_full_n,
        inv_sum_exp_stream_write => Loop_divide_proc_U0_inv_sum_exp_stream_write,
        inv_sum_exp_stream_num_data_valid => Loop_divide_proc_U0_inv_sum_exp_stream_num_data_valid,
        inv_sum_exp_stream_fifo_cap => Loop_divide_proc_U0_inv_sum_exp_stream_fifo_cap);

    Loop_softmax_output_proc_U0 : component Softmax_Loop_softmax_output_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_softmax_output_proc_U0_ap_start,
        ap_done => Loop_softmax_output_proc_U0_ap_done,
        ap_continue => Loop_softmax_output_proc_U0_ap_continue,
        ap_idle => Loop_softmax_output_proc_U0_ap_idle,
        ap_ready => Loop_softmax_output_proc_U0_ap_ready,
        inv_sum_exp_stream_dout => inv_sum_exp_stream_dout,
        inv_sum_exp_stream_empty_n => inv_sum_exp_stream_empty_n,
        inv_sum_exp_stream_read => Loop_softmax_output_proc_U0_inv_sum_exp_stream_read,
        inv_sum_exp_stream_num_data_valid => inv_sum_exp_stream_num_data_valid,
        inv_sum_exp_stream_fifo_cap => inv_sum_exp_stream_fifo_cap,
        seq_len_dout => seq_len_c_dout,
        seq_len_empty_n => seq_len_c_empty_n,
        seq_len_read => Loop_softmax_output_proc_U0_seq_len_read,
        seq_len_num_data_valid => seq_len_c_num_data_valid,
        seq_len_fifo_cap => seq_len_c_fifo_cap,
        exp_bypass_stream_dout => exp_bypass_stream_dout,
        exp_bypass_stream_empty_n => exp_bypass_stream_empty_n,
        exp_bypass_stream_read => Loop_softmax_output_proc_U0_exp_bypass_stream_read,
        exp_bypass_stream_num_data_valid => exp_bypass_stream_num_data_valid,
        exp_bypass_stream_fifo_cap => exp_bypass_stream_fifo_cap,
        out_stream_TDATA => Loop_softmax_output_proc_U0_out_stream_TDATA,
        out_stream_TVALID => Loop_softmax_output_proc_U0_out_stream_TVALID,
        out_stream_TREADY => out_stream_TREADY);

    max_value_stream_U : component Softmax_fifo_w16_d128_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_max_value_proc_U0_max_value_stream_din,
        if_full_n => max_value_stream_full_n,
        if_write => Loop_max_value_proc_U0_max_value_stream_write,
        if_dout => max_value_stream_dout,
        if_empty_n => max_value_stream_empty_n,
        if_read => Loop_sub_max_proc_U0_max_value_stream_read,
        if_num_data_valid => max_value_stream_num_data_valid,
        if_fifo_cap => max_value_stream_fifo_cap);

    max_bypass_stream_U : component Softmax_fifo_w16_d16384_U
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_max_value_proc_U0_max_bypass_stream_din,
        if_full_n => max_bypass_stream_full_n,
        if_write => Loop_max_value_proc_U0_max_bypass_stream_write,
        if_dout => max_bypass_stream_dout,
        if_empty_n => max_bypass_stream_empty_n,
        if_read => Loop_sub_max_proc_U0_max_bypass_stream_read,
        if_num_data_valid => max_bypass_stream_num_data_valid,
        if_fifo_cap => max_bypass_stream_fifo_cap);

    seq_len_c1_U : component Softmax_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_max_value_proc_U0_seq_len_c1_din,
        if_full_n => seq_len_c1_full_n,
        if_write => Loop_max_value_proc_U0_seq_len_c1_write,
        if_dout => seq_len_c1_dout,
        if_empty_n => seq_len_c1_empty_n,
        if_read => Loop_sub_max_proc_U0_seq_len_read,
        if_num_data_valid => seq_len_c1_num_data_valid,
        if_fifo_cap => seq_len_c1_fifo_cap);

    sum_exp_stream_U : component Softmax_fifo_w16_d128_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_sub_max_proc_U0_sum_exp_stream_din,
        if_full_n => sum_exp_stream_full_n,
        if_write => Loop_sub_max_proc_U0_sum_exp_stream_write,
        if_dout => sum_exp_stream_dout,
        if_empty_n => sum_exp_stream_empty_n,
        if_read => Loop_divide_proc_U0_sum_exp_stream_read,
        if_num_data_valid => sum_exp_stream_num_data_valid,
        if_fifo_cap => sum_exp_stream_fifo_cap);

    exp_bypass_stream_U : component Softmax_fifo_w16_d16384_U
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_sub_max_proc_U0_exp_bypass_stream_din,
        if_full_n => exp_bypass_stream_full_n,
        if_write => Loop_sub_max_proc_U0_exp_bypass_stream_write,
        if_dout => exp_bypass_stream_dout,
        if_empty_n => exp_bypass_stream_empty_n,
        if_read => Loop_softmax_output_proc_U0_exp_bypass_stream_read,
        if_num_data_valid => exp_bypass_stream_num_data_valid,
        if_fifo_cap => exp_bypass_stream_fifo_cap);

    seq_len_c_U : component Softmax_fifo_w32_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_sub_max_proc_U0_seq_len_c_din,
        if_full_n => seq_len_c_full_n,
        if_write => Loop_sub_max_proc_U0_seq_len_c_write,
        if_dout => seq_len_c_dout,
        if_empty_n => seq_len_c_empty_n,
        if_read => Loop_softmax_output_proc_U0_seq_len_read,
        if_num_data_valid => seq_len_c_num_data_valid,
        if_fifo_cap => seq_len_c_fifo_cap);

    inv_sum_exp_stream_U : component Softmax_fifo_w16_d128_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_divide_proc_U0_inv_sum_exp_stream_din,
        if_full_n => inv_sum_exp_stream_full_n,
        if_write => Loop_divide_proc_U0_inv_sum_exp_stream_write,
        if_dout => inv_sum_exp_stream_dout,
        if_empty_n => inv_sum_exp_stream_empty_n,
        if_read => Loop_softmax_output_proc_U0_inv_sum_exp_stream_read,
        if_num_data_valid => inv_sum_exp_stream_num_data_valid,
        if_fifo_cap => inv_sum_exp_stream_fifo_cap);

    start_for_Loop_sub_max_proc_U0_U : component Softmax_start_for_Loop_sub_max_proc_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Loop_sub_max_proc_U0_din,
        if_full_n => start_for_Loop_sub_max_proc_U0_full_n,
        if_write => Loop_max_value_proc_U0_start_write,
        if_dout => start_for_Loop_sub_max_proc_U0_dout,
        if_empty_n => start_for_Loop_sub_max_proc_U0_empty_n,
        if_read => Loop_sub_max_proc_U0_ap_ready);

    start_for_Loop_divide_proc_U0_U : component Softmax_start_for_Loop_divide_proc_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Loop_divide_proc_U0_din,
        if_full_n => start_for_Loop_divide_proc_U0_full_n,
        if_write => Loop_sub_max_proc_U0_start_write,
        if_dout => start_for_Loop_divide_proc_U0_dout,
        if_empty_n => start_for_Loop_divide_proc_U0_empty_n,
        if_read => Loop_divide_proc_U0_ap_ready);

    start_for_Loop_softmax_output_proc_U0_U : component Softmax_start_for_Loop_softmax_output_proc_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Loop_softmax_output_proc_U0_din,
        if_full_n => start_for_Loop_softmax_output_proc_U0_full_n,
        if_write => Loop_sub_max_proc_U0_start_write,
        if_dout => start_for_Loop_softmax_output_proc_U0_dout,
        if_empty_n => start_for_Loop_softmax_output_proc_U0_empty_n,
        if_read => Loop_softmax_output_proc_U0_ap_ready);




    Loop_divide_proc_U0_ap_continue <= ap_const_logic_1;
    Loop_divide_proc_U0_ap_start <= start_for_Loop_divide_proc_U0_empty_n;
    Loop_divide_proc_U0_inv_sum_exp_stream_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(inv_sum_exp_stream_fifo_cap),8))),32));
    Loop_divide_proc_U0_inv_sum_exp_stream_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(inv_sum_exp_stream_num_data_valid),8))),32));
    Loop_max_value_proc_U0_ap_continue <= ap_const_logic_1;
    Loop_max_value_proc_U0_ap_start <= ap_start;
    Loop_softmax_output_proc_U0_ap_continue <= ap_const_logic_1;
    Loop_softmax_output_proc_U0_ap_start <= start_for_Loop_softmax_output_proc_U0_empty_n;
    Loop_sub_max_proc_U0_ap_continue <= ap_const_logic_1;
    Loop_sub_max_proc_U0_ap_start <= start_for_Loop_sub_max_proc_U0_empty_n;
    Loop_sub_max_proc_U0_exp_bypass_stream_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_bypass_stream_fifo_cap),15))),32));
    Loop_sub_max_proc_U0_exp_bypass_stream_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_bypass_stream_num_data_valid),15))),32));
    Loop_sub_max_proc_U0_start_full_n <= (start_for_Loop_softmax_output_proc_U0_full_n and start_for_Loop_divide_proc_U0_full_n);
    ap_done <= Loop_softmax_output_proc_U0_ap_done;
    ap_idle <= (Loop_sub_max_proc_U0_ap_idle and Loop_softmax_output_proc_U0_ap_idle and Loop_max_value_proc_U0_ap_idle and Loop_divide_proc_U0_ap_idle);
    ap_ready <= Loop_max_value_proc_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    in_stream_TREADY <= Loop_max_value_proc_U0_in_stream_TREADY;
    out_stream_TDATA <= Loop_softmax_output_proc_U0_out_stream_TDATA;
    out_stream_TVALID <= Loop_softmax_output_proc_U0_out_stream_TVALID;
    start_for_Loop_divide_proc_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_Loop_softmax_output_proc_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_Loop_sub_max_proc_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
