-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Softmax_Loop_sub_max_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    max_value_stream_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    max_value_stream_empty_n : IN STD_LOGIC;
    max_value_stream_read : OUT STD_LOGIC;
    max_value_stream_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    max_value_stream_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    seq_len_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    seq_len_empty_n : IN STD_LOGIC;
    seq_len_read : OUT STD_LOGIC;
    seq_len_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    seq_len_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    sum_exp_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    sum_exp_stream_full_n : IN STD_LOGIC;
    sum_exp_stream_write : OUT STD_LOGIC;
    sum_exp_stream_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    sum_exp_stream_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    max_bypass_stream_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    max_bypass_stream_empty_n : IN STD_LOGIC;
    max_bypass_stream_read : OUT STD_LOGIC;
    max_bypass_stream_num_data_valid : IN STD_LOGIC_VECTOR (14 downto 0);
    max_bypass_stream_fifo_cap : IN STD_LOGIC_VECTOR (14 downto 0);
    exp_bypass_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    exp_bypass_stream_full_n : IN STD_LOGIC;
    exp_bypass_stream_write : OUT STD_LOGIC;
    exp_bypass_stream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    exp_bypass_stream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    seq_len_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    seq_len_c_full_n : IN STD_LOGIC;
    seq_len_c_write : OUT STD_LOGIC;
    seq_len_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    seq_len_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of Softmax_Loop_sub_max_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_35 : STD_LOGIC_VECTOR (5 downto 0) := "110101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_34 : STD_LOGIC_VECTOR (5 downto 0) := "110100";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal max_value_stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln52_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal seq_len_blk_n : STD_LOGIC;
    signal sum_exp_stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal seq_len_c_blk_n : STD_LOGIC;
    signal seq_len_read_reg_529 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal max_val_fu_198_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal max_val_reg_537 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal icmp_ln70_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_reg_542 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_fu_245_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_547 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln70_fu_259_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln70_reg_552 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln70_fu_275_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_reg_560 : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln70_1_reg_566 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_17_reg_571 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_start : STD_LOGIC;
    signal grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_done : STD_LOGIC;
    signal grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_idle : STD_LOGIC;
    signal grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_ready : STD_LOGIC;
    signal grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_max_bypass_stream_read : STD_LOGIC;
    signal grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_exp_bypass_stream_din : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_exp_bypass_stream_write : STD_LOGIC;
    signal grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_sum_exp_acc_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_sum_exp_acc_out_ap_vld : STD_LOGIC;
    signal grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state2_ignore_call6 : BOOLEAN;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal head_fu_126 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal head_2_fu_186_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal seq_len_read_local : STD_LOGIC;
    signal seq_len_c_write_local : STD_LOGIC;
    signal max_value_stream_read_local : STD_LOGIC;
    signal empty_fu_504_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_exp_stream_write_local : STD_LOGIC;
    signal sub_ln70_fu_253_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_267_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_267_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln70_fu_279_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln70_1_fu_282_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln70_fu_292_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_13_fu_302_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_1_fu_288_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln70_4_fu_318_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln70_3_fu_324_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln70_2_fu_328_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln70_fu_334_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln70_1_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_2_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_351_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_365_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_16_fu_365_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln70_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_ln70_1_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_ln70_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln70_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln70_1_fu_394_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln70_fu_400_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln70_2_fu_409_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln70_1_fu_415_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln70_fu_404_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln70_fu_419_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln70_3_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln70_3_fu_424_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln70_4_fu_428_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln70_1_fu_432_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln70_1_fu_384_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln70_2_fu_440_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln70_3_fu_474_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln70_2_fu_467_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln70_3_fu_479_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln70_2_fu_464_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_485_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_492_p5 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal tmp_6_fu_267_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_365_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component Softmax_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        max_bypass_stream_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        max_bypass_stream_empty_n : IN STD_LOGIC;
        max_bypass_stream_read : OUT STD_LOGIC;
        max_bypass_stream_num_data_valid : IN STD_LOGIC_VECTOR (14 downto 0);
        max_bypass_stream_fifo_cap : IN STD_LOGIC_VECTOR (14 downto 0);
        exp_bypass_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        exp_bypass_stream_full_n : IN STD_LOGIC;
        exp_bypass_stream_write : OUT STD_LOGIC;
        exp_bypass_stream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        exp_bypass_stream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        seq_len_load : IN STD_LOGIC_VECTOR (31 downto 0);
        max_val : IN STD_LOGIC_VECTOR (15 downto 0);
        sum_exp_acc_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_exp_acc_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Softmax_ctlz_32_32_1_1 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Softmax_bitselect_1ns_32ns_5ns_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161 : component Softmax_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_start,
        ap_done => grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_done,
        ap_idle => grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_idle,
        ap_ready => grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_ready,
        max_bypass_stream_dout => max_bypass_stream_dout,
        max_bypass_stream_empty_n => max_bypass_stream_empty_n,
        max_bypass_stream_read => grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_max_bypass_stream_read,
        max_bypass_stream_num_data_valid => ap_const_lv15_0,
        max_bypass_stream_fifo_cap => ap_const_lv15_0,
        exp_bypass_stream_din => grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_exp_bypass_stream_din,
        exp_bypass_stream_full_n => exp_bypass_stream_full_n,
        exp_bypass_stream_write => grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_exp_bypass_stream_write,
        exp_bypass_stream_num_data_valid => exp_bypass_stream_num_data_valid,
        exp_bypass_stream_fifo_cap => exp_bypass_stream_fifo_cap,
        seq_len_load => seq_len_read_reg_529,
        max_val => max_val_reg_537,
        sum_exp_acc_out => grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_sum_exp_acc_out,
        sum_exp_acc_out_ap_vld => grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_sum_exp_acc_out_ap_vld);

    ctlz_32_32_1_1_U36 : component Softmax_ctlz_32_32_1_1
    generic map (
        din_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din => tmp_6_fu_267_p1,
        dout => tmp_6_fu_267_p3);

    bitselect_1ns_32ns_5ns_1_1_1_U37 : component Softmax_bitselect_1ns_32ns_5ns_1_1_1
    generic map (
        DATAWIDTH => 32,
        ADDRWIDTH => 5)
    port map (
        din => select_ln70_reg_552,
        sel => tmp_16_fu_365_p2,
        dout => tmp_16_fu_365_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln52_fu_192_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln52_fu_192_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_ignore_call6))) then 
                    grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_ready = ap_const_logic_1)) then 
                    grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    head_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                head_fu_126 <= ap_const_lv3_0;
            elsif (((icmp_ln52_fu_192_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
                head_fu_126 <= head_2_fu_186_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln70_reg_542 <= icmp_ln70_fu_239_p2;
                select_ln70_reg_552 <= select_ln70_fu_259_p3;
                tmp_reg_547 <= grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_sum_exp_acc_out(31 downto 31);
                trunc_ln70_reg_560 <= trunc_ln70_fu_275_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                lshr_ln70_1_reg_566 <= add_ln70_2_fu_440_p2(15 downto 1);
                tmp_17_reg_571 <= add_ln70_2_fu_440_p2(12 downto 12);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then
                max_val_reg_537 <= max_val_fu_198_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                seq_len_read_reg_529 <= seq_len_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, sum_exp_stream_full_n, ap_CS_fsm_state2, icmp_ln52_fu_192_p2, ap_CS_fsm_state6, ap_block_state1, ap_block_state2, grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln52_fu_192_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((icmp_ln52_fu_192_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((sum_exp_stream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln70_1_fu_394_p2 <= std_logic_vector(unsigned(sub_ln70_1_fu_282_p2) + unsigned(ap_const_lv6_34));
    add_ln70_2_fu_440_p2 <= std_logic_vector(unsigned(select_ln70_1_fu_432_p3) + unsigned(zext_ln70_1_fu_384_p1));
    add_ln70_3_fu_479_p2 <= std_logic_vector(unsigned(sub_ln70_3_fu_474_p2) + unsigned(select_ln70_2_fu_467_p3));
    add_ln70_fu_292_p2 <= std_logic_vector(unsigned(sub_ln70_1_fu_282_p2) + unsigned(ap_const_lv6_35));
    and_ln70_fu_334_p2 <= (select_ln70_reg_552 and lshr_ln70_2_fu_328_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2)
    begin
        if ((ap_const_boolean_1 = ap_block_state2)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_done)
    begin
        if ((grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(sum_exp_stream_full_n)
    begin
        if ((sum_exp_stream_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, seq_len_empty_n, seq_len_c_full_n)
    begin
                ap_block_state1 <= ((seq_len_c_full_n = ap_const_logic_0) or (seq_len_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(max_value_stream_empty_n, icmp_ln52_fu_192_p2)
    begin
                ap_block_state2 <= ((icmp_ln52_fu_192_p2 = ap_const_lv1_0) and (max_value_stream_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_ignore_call6_assign_proc : process(max_value_stream_empty_n, icmp_ln52_fu_192_p2)
    begin
                ap_block_state2_ignore_call6 <= ((icmp_ln52_fu_192_p2 = ap_const_lv1_0) and (max_value_stream_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln52_fu_192_p2, ap_block_state2)
    begin
        if (((icmp_ln52_fu_192_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    empty_fu_504_p3 <= 
        ap_const_lv16_0 when (icmp_ln70_reg_542(0) = '1') else 
        tmp_s_fu_492_p5;
    exp_bypass_stream_din <= grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_exp_bypass_stream_din;
    exp_bypass_stream_write <= grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_exp_bypass_stream_write;
    grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_start <= grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_ap_start_reg;
    head_2_fu_186_p2 <= std_logic_vector(unsigned(head_fu_126) + unsigned(ap_const_lv3_1));
    icmp_ln52_fu_192_p2 <= "1" when (head_fu_126 = ap_const_lv3_4) else "0";
    icmp_ln70_1_fu_312_p2 <= "1" when (signed(tmp_13_fu_302_p4) > signed(ap_const_lv5_0)) else "0";
    icmp_ln70_2_fu_339_p2 <= "0" when (and_ln70_fu_334_p2 = ap_const_lv32_0) else "1";
    icmp_ln70_3_fu_388_p2 <= "1" when (signed(add_ln70_fu_292_p2) > signed(ap_const_lv6_0)) else "0";
    icmp_ln70_fu_239_p2 <= "1" when (grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_sum_exp_acc_out = ap_const_lv32_0) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln52_fu_192_p2, ap_block_state2)
    begin
        if (((icmp_ln52_fu_192_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln70_2_fu_328_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv32_FFFFFFFF),to_integer(unsigned('0' & zext_ln70_3_fu_324_p1(31-1 downto 0)))));
    lshr_ln70_fu_404_p2 <= std_logic_vector(shift_right(unsigned(select_ln70_reg_552),to_integer(unsigned('0' & sext_ln70_fu_400_p1(31-1 downto 0)))));
    max_bypass_stream_read <= grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_max_bypass_stream_read;
    max_val_fu_198_p1 <= max_value_stream_dout;

    max_value_stream_blk_n_assign_proc : process(max_value_stream_empty_n, ap_CS_fsm_state2, icmp_ln52_fu_192_p2)
    begin
        if (((icmp_ln52_fu_192_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            max_value_stream_blk_n <= max_value_stream_empty_n;
        else 
            max_value_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    max_value_stream_read <= max_value_stream_read_local;

    max_value_stream_read_local_assign_proc : process(ap_CS_fsm_state2, icmp_ln52_fu_192_p2, ap_block_state2)
    begin
        if (((icmp_ln52_fu_192_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
            max_value_stream_read_local <= ap_const_logic_1;
        else 
            max_value_stream_read_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln70_fu_378_p2 <= (phi_ln70_fu_345_p2 or phi_ln70_1_fu_372_p2);
    phi_ln70_1_fu_372_p2 <= (xor_ln70_fu_359_p2 and tmp_16_fu_365_p3);
    phi_ln70_fu_345_p2 <= (icmp_ln70_2_fu_339_p2 and icmp_ln70_1_fu_312_p2);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln70_1_fu_432_p3 <= 
        trunc_ln70_3_fu_424_p1 when (icmp_ln70_3_fu_388_p2(0) = '1') else 
        trunc_ln70_4_fu_428_p1;
    select_ln70_2_fu_467_p3 <= 
        ap_const_lv5_F when (tmp_17_reg_571(0) = '1') else 
        ap_const_lv5_E;
    select_ln70_fu_259_p3 <= 
        sub_ln70_fu_253_p2 when (tmp_fu_245_p3(0) = '1') else 
        grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_sum_exp_acc_out;

    seq_len_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, seq_len_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            seq_len_blk_n <= seq_len_empty_n;
        else 
            seq_len_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    seq_len_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, seq_len_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            seq_len_c_blk_n <= seq_len_c_full_n;
        else 
            seq_len_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    seq_len_c_din <= seq_len_dout;
    seq_len_c_write <= seq_len_c_write_local;

    seq_len_c_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            seq_len_c_write_local <= ap_const_logic_1;
        else 
            seq_len_c_write_local <= ap_const_logic_0;
        end if; 
    end process;

    seq_len_read <= seq_len_read_local;

    seq_len_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            seq_len_read_local <= ap_const_logic_1;
        else 
            seq_len_read_local <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln70_1_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln70_2_fu_409_p2),32));

        sext_ln70_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln70_1_fu_394_p2),32));

    shl_ln70_fu_419_p2 <= std_logic_vector(shift_left(unsigned(select_ln70_reg_552),to_integer(unsigned('0' & sext_ln70_1_fu_415_p1(31-1 downto 0)))));
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln70_1_fu_282_p2 <= std_logic_vector(signed(ap_const_lv6_20) - signed(zext_ln70_fu_279_p1));
    sub_ln70_2_fu_409_p2 <= std_logic_vector(unsigned(ap_const_lv6_C) - unsigned(sub_ln70_1_fu_282_p2));
    sub_ln70_3_fu_474_p2 <= std_logic_vector(signed(ap_const_lv5_10) - signed(trunc_ln70_reg_560));
    sub_ln70_4_fu_318_p2 <= std_logic_vector(unsigned(ap_const_lv5_C) - unsigned(trunc_ln70_1_fu_288_p1));
    sub_ln70_fu_253_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_sum_exp_acc_out));

    sum_exp_stream_blk_n_assign_proc : process(sum_exp_stream_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            sum_exp_stream_blk_n <= sum_exp_stream_full_n;
        else 
            sum_exp_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sum_exp_stream_din <= empty_fu_504_p3;
    sum_exp_stream_write <= sum_exp_stream_write_local;

    sum_exp_stream_write_local_assign_proc : process(sum_exp_stream_full_n, ap_CS_fsm_state6)
    begin
        if (((sum_exp_stream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            sum_exp_stream_write_local <= ap_const_logic_1;
        else 
            sum_exp_stream_write_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_13_fu_302_p4 <= add_ln70_fu_292_p2(5 downto 1);
    tmp_14_fu_351_p3 <= add_ln70_fu_292_p2(5 downto 5);
    tmp_16_fu_365_p2 <= add_ln70_fu_292_p2(5 - 1 downto 0);
    tmp_1_fu_485_p3 <= (tmp_reg_547 & add_ln70_3_fu_479_p2);
    tmp_6_fu_267_p1 <= 
        sub_ln70_fu_253_p2 when (tmp_fu_245_p3(0) = '1') else 
        grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_sum_exp_acc_out;
    tmp_fu_245_p3 <= grp_Loop_sub_max_proc_Pipeline_VITIS_LOOP_57_2_fu_161_sum_exp_acc_out(31 downto 31);
    tmp_s_fu_492_p5 <= (tmp_1_fu_485_p3 & zext_ln70_2_fu_464_p1(9 downto 0));
    trunc_ln70_1_fu_288_p1 <= sub_ln70_1_fu_282_p2(5 - 1 downto 0);
    trunc_ln70_3_fu_424_p1 <= lshr_ln70_fu_404_p2(16 - 1 downto 0);
    trunc_ln70_4_fu_428_p1 <= shl_ln70_fu_419_p2(16 - 1 downto 0);
    trunc_ln70_fu_275_p1 <= tmp_6_fu_267_p3(5 - 1 downto 0);
    xor_ln70_fu_359_p2 <= (tmp_14_fu_351_p3 xor ap_const_lv1_1);
    zext_ln70_1_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln70_fu_378_p2),16));
    zext_ln70_2_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln70_1_reg_566),16));
    zext_ln70_3_fu_324_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln70_4_fu_318_p2),32));
    zext_ln70_fu_279_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln70_reg_560),6));
end behav;
