// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Gemv_Test_Block_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        rows,
        cols,
        rows_c1_din,
        rows_c1_full_n,
        rows_c1_write,
        rows_c1_num_data_valid,
        rows_c1_fifo_cap,
        rows_c2_din,
        rows_c2_full_n,
        rows_c2_write,
        rows_c2_num_data_valid,
        rows_c2_fifo_cap,
        rows_c3_din,
        rows_c3_full_n,
        rows_c3_write,
        rows_c3_num_data_valid,
        rows_c3_fifo_cap,
        rows_c4_din,
        rows_c4_full_n,
        rows_c4_write,
        rows_c4_num_data_valid,
        rows_c4_fifo_cap,
        cols_c_din,
        cols_c_full_n,
        cols_c_write,
        cols_c_num_data_valid,
        cols_c_fifo_cap,
        cols_c5_din,
        cols_c5_full_n,
        cols_c5_write,
        cols_c5_num_data_valid,
        cols_c5_fifo_cap,
        cols_c6_din,
        cols_c6_full_n,
        cols_c6_write,
        cols_c6_num_data_valid,
        cols_c6_fifo_cap,
        cols_c7_din,
        cols_c7_full_n,
        cols_c7_write,
        cols_c7_num_data_valid,
        cols_c7_fifo_cap,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] rows;
input  [31:0] cols;
output  [31:0] rows_c1_din;
input   rows_c1_full_n;
output   rows_c1_write;
input  [2:0] rows_c1_num_data_valid;
input  [2:0] rows_c1_fifo_cap;
output  [31:0] rows_c2_din;
input   rows_c2_full_n;
output   rows_c2_write;
input  [2:0] rows_c2_num_data_valid;
input  [2:0] rows_c2_fifo_cap;
output  [31:0] rows_c3_din;
input   rows_c3_full_n;
output   rows_c3_write;
input  [2:0] rows_c3_num_data_valid;
input  [2:0] rows_c3_fifo_cap;
output  [31:0] rows_c4_din;
input   rows_c4_full_n;
output   rows_c4_write;
input  [2:0] rows_c4_num_data_valid;
input  [2:0] rows_c4_fifo_cap;
output  [31:0] cols_c_din;
input   cols_c_full_n;
output   cols_c_write;
input  [2:0] cols_c_num_data_valid;
input  [2:0] cols_c_fifo_cap;
output  [31:0] cols_c5_din;
input   cols_c5_full_n;
output   cols_c5_write;
input  [2:0] cols_c5_num_data_valid;
input  [2:0] cols_c5_fifo_cap;
output  [31:0] cols_c6_din;
input   cols_c6_full_n;
output   cols_c6_write;
input  [2:0] cols_c6_num_data_valid;
input  [2:0] cols_c6_fifo_cap;
output  [31:0] cols_c7_din;
input   cols_c7_full_n;
output   cols_c7_write;
input  [2:0] cols_c7_num_data_valid;
input  [2:0] cols_c7_fifo_cap;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;

reg ap_done;
reg ap_idle;
reg start_write;
reg[31:0] ap_return_0;
reg[31:0] ap_return_1;
reg[31:0] ap_return_2;
reg[31:0] ap_return_3;
reg[31:0] ap_return_4;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    rows_c1_blk_n;
reg    rows_c2_blk_n;
reg    rows_c3_blk_n;
reg    rows_c4_blk_n;
reg    cols_c_blk_n;
reg    cols_c5_blk_n;
reg    cols_c6_blk_n;
reg    cols_c7_blk_n;
reg    ap_block_state1;
reg    cols_c7_write_local;
reg    cols_c6_write_local;
reg    cols_c5_write_local;
reg    cols_c_write_local;
reg    rows_c4_write_local;
reg    rows_c3_write_local;
reg    rows_c2_write_local;
reg    rows_c1_write_local;
wire   [31:0] mul_ln59_fu_118_p2;
reg   [31:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [31:0] ap_return_2_preg;
reg   [31:0] ap_return_3_preg;
reg   [31:0] ap_return_4_preg;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 32'd0;
#0 ap_return_2_preg = 32'd0;
#0 ap_return_3_preg = 32'd0;
#0 ap_return_4_preg = 32'd0;
end

Gemv_Test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U13(
    .din0(cols),
    .din1(rows),
    .dout(mul_ln59_fu_118_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_return_0_preg <= mul_ln59_fu_118_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_return_1_preg <= mul_ln59_fu_118_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_return_2_preg <= mul_ln59_fu_118_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_return_3_preg <= mul_ln59_fu_118_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_return_4_preg <= mul_ln59_fu_118_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        ap_return_0 = mul_ln59_fu_118_p2;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        ap_return_1 = mul_ln59_fu_118_p2;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        ap_return_2 = mul_ln59_fu_118_p2;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        ap_return_3 = mul_ln59_fu_118_p2;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        ap_return_4 = mul_ln59_fu_118_p2;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_c5_blk_n = cols_c5_full_n;
    end else begin
        cols_c5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        cols_c5_write_local = 1'b1;
    end else begin
        cols_c5_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_c6_blk_n = cols_c6_full_n;
    end else begin
        cols_c6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        cols_c6_write_local = 1'b1;
    end else begin
        cols_c6_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_c7_blk_n = cols_c7_full_n;
    end else begin
        cols_c7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        cols_c7_write_local = 1'b1;
    end else begin
        cols_c7_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_c_blk_n = cols_c_full_n;
    end else begin
        cols_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        cols_c_write_local = 1'b1;
    end else begin
        cols_c_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rows_c1_blk_n = rows_c1_full_n;
    end else begin
        rows_c1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rows_c1_write_local = 1'b1;
    end else begin
        rows_c1_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rows_c2_blk_n = rows_c2_full_n;
    end else begin
        rows_c2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rows_c2_write_local = 1'b1;
    end else begin
        rows_c2_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rows_c3_blk_n = rows_c3_full_n;
    end else begin
        rows_c3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rows_c3_write_local = 1'b1;
    end else begin
        rows_c3_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rows_c4_blk_n = rows_c4_full_n;
    end else begin
        rows_c4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rows_c4_write_local = 1'b1;
    end else begin
        rows_c4_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((cols_c7_full_n == 1'b0) | (real_start == 1'b0) | (cols_c6_full_n == 1'b0) | (cols_c5_full_n == 1'b0) | (cols_c_full_n == 1'b0) | (rows_c4_full_n == 1'b0) | (rows_c3_full_n == 1'b0) | (rows_c2_full_n == 1'b0) | (rows_c1_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign cols_c5_din = cols;

assign cols_c5_write = cols_c5_write_local;

assign cols_c6_din = cols;

assign cols_c6_write = cols_c6_write_local;

assign cols_c7_din = cols;

assign cols_c7_write = cols_c7_write_local;

assign cols_c_din = cols;

assign cols_c_write = cols_c_write_local;

assign rows_c1_din = rows;

assign rows_c1_write = rows_c1_write_local;

assign rows_c2_din = rows;

assign rows_c2_write = rows_c2_write_local;

assign rows_c3_din = rows;

assign rows_c3_write = rows_c3_write_local;

assign rows_c4_din = rows;

assign rows_c4_write = rows_c4_write_local;

assign start_out = real_start;

endmodule //Gemv_Test_Block_entry_proc
