// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Gemv_Test_Mul_Adder_Tree_128_Loop_adder_16_8_proc_5_Pipeline_adder_16_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pass_16_i_dout,
        pass_16_i_empty_n,
        pass_16_i_read,
        pass_16_i_num_data_valid,
        pass_16_i_fifo_cap,
        pass_8_i_din,
        pass_8_i_full_n,
        pass_8_i_write,
        pass_8_i_num_data_valid,
        pass_8_i_fifo_cap,
        select_ln59
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [255:0] pass_16_i_dout;
input   pass_16_i_empty_n;
output   pass_16_i_read;
input  [2:0] pass_16_i_num_data_valid;
input  [2:0] pass_16_i_fifo_cap;
output  [127:0] pass_8_i_din;
input   pass_8_i_full_n;
output   pass_8_i_write;
input  [31:0] pass_8_i_num_data_valid;
input  [31:0] pass_8_i_fifo_cap;
input  [22:0] select_ln59;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln139_fu_177_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    pass_16_i_blk_n;
wire    ap_block_pp0_stage0;
reg    pass_8_i_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] bitcast_ln142_fu_350_p1;
wire   [15:0] bitcast_ln142_1_fu_354_p1;
wire   [15:0] bitcast_ln142_2_fu_358_p1;
wire   [15:0] bitcast_ln142_3_fu_362_p1;
wire   [15:0] bitcast_ln142_4_fu_366_p1;
wire   [15:0] bitcast_ln142_5_fu_370_p1;
wire   [15:0] bitcast_ln142_6_fu_374_p1;
wire   [15:0] bitcast_ln142_7_fu_378_p1;
wire   [15:0] bitcast_ln142_8_fu_382_p1;
wire   [15:0] bitcast_ln142_9_fu_386_p1;
wire   [15:0] bitcast_ln142_10_fu_390_p1;
wire   [15:0] bitcast_ln142_11_fu_394_p1;
wire   [15:0] bitcast_ln142_12_fu_398_p1;
wire   [15:0] bitcast_ln142_13_fu_402_p1;
wire   [15:0] bitcast_ln142_14_fu_406_p1;
wire   [15:0] bitcast_ln142_15_fu_410_p1;
reg   [21:0] iter_fu_110;
wire   [21:0] add_ln139_fu_183_p2;
wire    ap_loop_init;
reg   [21:0] ap_sig_allocacmp_iter_load;
reg    pass_16_i_read_local;
wire   [127:0] or_ln148_s_fu_510_p9;
reg    ap_block_pp0_stage0_01001;
reg    pass_8_i_write_local;
reg   [15:0] grp_fu_133_p0;
reg   [15:0] grp_fu_133_p1;
reg   [15:0] grp_fu_137_p0;
reg   [15:0] grp_fu_137_p1;
reg   [15:0] grp_fu_141_p0;
reg   [15:0] grp_fu_141_p1;
reg   [15:0] grp_fu_145_p0;
reg   [15:0] grp_fu_145_p1;
reg   [15:0] grp_fu_149_p0;
reg   [15:0] grp_fu_149_p1;
reg   [15:0] grp_fu_153_p0;
reg   [15:0] grp_fu_153_p1;
reg   [15:0] grp_fu_157_p0;
reg   [15:0] grp_fu_157_p1;
reg   [15:0] grp_fu_161_p0;
reg   [15:0] grp_fu_161_p1;
wire   [22:0] iter_cast_fu_173_p1;
wire   [15:0] trunc_ln142_fu_196_p1;
wire   [15:0] trunc_ln142_1_fu_200_p4;
wire   [15:0] trunc_ln142_2_fu_210_p4;
wire   [15:0] trunc_ln142_3_fu_220_p4;
wire   [15:0] trunc_ln142_4_fu_230_p4;
wire   [15:0] trunc_ln142_5_fu_240_p4;
wire   [15:0] trunc_ln142_6_fu_250_p4;
wire   [15:0] trunc_ln142_7_fu_260_p4;
wire   [15:0] trunc_ln142_8_fu_270_p4;
wire   [15:0] trunc_ln142_9_fu_280_p4;
wire   [15:0] trunc_ln142_s_fu_290_p4;
wire   [15:0] trunc_ln142_10_fu_300_p4;
wire   [15:0] trunc_ln142_11_fu_310_p4;
wire   [15:0] trunc_ln142_12_fu_320_p4;
wire   [15:0] trunc_ln142_13_fu_330_p4;
wire   [15:0] trunc_ln142_14_fu_340_p4;
reg   [15:0] grp_fu_133_p2;
reg   [15:0] grp_fu_137_p2;
reg   [15:0] grp_fu_141_p2;
reg   [15:0] grp_fu_145_p2;
reg   [15:0] grp_fu_149_p2;
reg   [15:0] grp_fu_153_p2;
reg   [15:0] grp_fu_157_p2;
reg   [15:0] grp_fu_161_p2;
wire   [15:0] bitcast_ln148_7_fu_506_p1;
wire   [15:0] bitcast_ln148_6_fu_502_p1;
wire   [15:0] bitcast_ln148_5_fu_498_p1;
wire   [15:0] bitcast_ln148_4_fu_494_p1;
wire   [15:0] bitcast_ln148_3_fu_490_p1;
wire   [15:0] bitcast_ln148_2_fu_486_p1;
wire   [15:0] bitcast_ln148_1_fu_482_p1;
wire   [15:0] bitcast_ln148_fu_478_p1;
reg    grp_fu_133_ce;
wire   [15:0] pre_grp_fu_133_p2;
reg   [15:0] pre_grp_fu_133_p2_reg;
reg    grp_fu_137_ce;
wire   [15:0] pre_grp_fu_137_p2;
reg   [15:0] pre_grp_fu_137_p2_reg;
reg    grp_fu_141_ce;
wire   [15:0] pre_grp_fu_141_p2;
reg   [15:0] pre_grp_fu_141_p2_reg;
reg    grp_fu_145_ce;
wire   [15:0] pre_grp_fu_145_p2;
reg   [15:0] pre_grp_fu_145_p2_reg;
reg    grp_fu_149_ce;
wire   [15:0] pre_grp_fu_149_p2;
reg   [15:0] pre_grp_fu_149_p2_reg;
reg    grp_fu_153_ce;
wire   [15:0] pre_grp_fu_153_p2;
reg   [15:0] pre_grp_fu_153_p2_reg;
reg    grp_fu_157_ce;
wire   [15:0] pre_grp_fu_157_p2;
reg   [15:0] pre_grp_fu_157_p2_reg;
reg    grp_fu_161_ce;
wire   [15:0] pre_grp_fu_161_p2;
reg   [15:0] pre_grp_fu_161_p2_reg;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 iter_fu_110 = 22'd0;
#0 ap_done_reg = 1'b0;
end

Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_3_no_dsp_1_U626(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_133_p0),
    .din1(grp_fu_133_p1),
    .ce(grp_fu_133_ce),
    .dout(pre_grp_fu_133_p2)
);

Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_3_no_dsp_1_U627(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_137_p0),
    .din1(grp_fu_137_p1),
    .ce(grp_fu_137_ce),
    .dout(pre_grp_fu_137_p2)
);

Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_3_no_dsp_1_U628(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_141_p0),
    .din1(grp_fu_141_p1),
    .ce(grp_fu_141_ce),
    .dout(pre_grp_fu_141_p2)
);

Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_3_no_dsp_1_U629(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_145_p0),
    .din1(grp_fu_145_p1),
    .ce(grp_fu_145_ce),
    .dout(pre_grp_fu_145_p2)
);

Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_3_no_dsp_1_U630(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_149_p0),
    .din1(grp_fu_149_p1),
    .ce(grp_fu_149_ce),
    .dout(pre_grp_fu_149_p2)
);

Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_3_no_dsp_1_U631(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_153_p0),
    .din1(grp_fu_153_p1),
    .ce(grp_fu_153_ce),
    .dout(pre_grp_fu_153_p2)
);

Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_3_no_dsp_1_U632(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_157_p0),
    .din1(grp_fu_157_p1),
    .ce(grp_fu_157_ce),
    .dout(pre_grp_fu_157_p2)
);

Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_3_no_dsp_1_U633(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_161_p0),
    .din1(grp_fu_161_p1),
    .ce(grp_fu_161_ce),
    .dout(pre_grp_fu_161_p2)
);

Gemv_Test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_133_ce <= 1'b1;
    end else begin
        grp_fu_133_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_137_ce <= 1'b1;
    end else begin
        grp_fu_137_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_141_ce <= 1'b1;
    end else begin
        grp_fu_141_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_145_ce <= 1'b1;
    end else begin
        grp_fu_145_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_149_ce <= 1'b1;
    end else begin
        grp_fu_149_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_153_ce <= 1'b1;
    end else begin
        grp_fu_153_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_157_ce <= 1'b1;
    end else begin
        grp_fu_157_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_161_ce <= 1'b1;
    end else begin
        grp_fu_161_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln139_fu_177_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            iter_fu_110 <= add_ln139_fu_183_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            iter_fu_110 <= 22'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_133_p0 <= bitcast_ln142_fu_350_p1;
        grp_fu_133_p1 <= bitcast_ln142_1_fu_354_p1;
        grp_fu_137_p0 <= bitcast_ln142_2_fu_358_p1;
        grp_fu_137_p1 <= bitcast_ln142_3_fu_362_p1;
        grp_fu_141_p0 <= bitcast_ln142_4_fu_366_p1;
        grp_fu_141_p1 <= bitcast_ln142_5_fu_370_p1;
        grp_fu_145_p0 <= bitcast_ln142_6_fu_374_p1;
        grp_fu_145_p1 <= bitcast_ln142_7_fu_378_p1;
        grp_fu_149_p0 <= bitcast_ln142_8_fu_382_p1;
        grp_fu_149_p1 <= bitcast_ln142_9_fu_386_p1;
        grp_fu_153_p0 <= bitcast_ln142_10_fu_390_p1;
        grp_fu_153_p1 <= bitcast_ln142_11_fu_394_p1;
        grp_fu_157_p0 <= bitcast_ln142_12_fu_398_p1;
        grp_fu_157_p1 <= bitcast_ln142_13_fu_402_p1;
        grp_fu_161_p0 <= bitcast_ln142_14_fu_406_p1;
        grp_fu_161_p1 <= bitcast_ln142_15_fu_410_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_133_ce == 1'b1)) begin
        pre_grp_fu_133_p2_reg <= pre_grp_fu_133_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_137_ce == 1'b1)) begin
        pre_grp_fu_137_p2_reg <= pre_grp_fu_137_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_141_ce == 1'b1)) begin
        pre_grp_fu_141_p2_reg <= pre_grp_fu_141_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_145_ce == 1'b1)) begin
        pre_grp_fu_145_p2_reg <= pre_grp_fu_145_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_149_ce == 1'b1)) begin
        pre_grp_fu_149_p2_reg <= pre_grp_fu_149_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_153_ce == 1'b1)) begin
        pre_grp_fu_153_p2_reg <= pre_grp_fu_153_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_157_ce == 1'b1)) begin
        pre_grp_fu_157_p2_reg <= pre_grp_fu_157_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_161_ce == 1'b1)) begin
        pre_grp_fu_161_p2_reg <= pre_grp_fu_161_p2;
    end
end

always @ (*) begin
    if (((icmp_ln139_fu_177_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_iter_load = 22'd0;
    end else begin
        ap_sig_allocacmp_iter_load = iter_fu_110;
    end
end

always @ (*) begin
    if ((grp_fu_133_ce == 1'b1)) begin
        grp_fu_133_p2 = pre_grp_fu_133_p2;
    end else begin
        grp_fu_133_p2 = pre_grp_fu_133_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_137_ce == 1'b1)) begin
        grp_fu_137_p2 = pre_grp_fu_137_p2;
    end else begin
        grp_fu_137_p2 = pre_grp_fu_137_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_141_ce == 1'b1)) begin
        grp_fu_141_p2 = pre_grp_fu_141_p2;
    end else begin
        grp_fu_141_p2 = pre_grp_fu_141_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_145_ce == 1'b1)) begin
        grp_fu_145_p2 = pre_grp_fu_145_p2;
    end else begin
        grp_fu_145_p2 = pre_grp_fu_145_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_149_ce == 1'b1)) begin
        grp_fu_149_p2 = pre_grp_fu_149_p2;
    end else begin
        grp_fu_149_p2 = pre_grp_fu_149_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_153_ce == 1'b1)) begin
        grp_fu_153_p2 = pre_grp_fu_153_p2;
    end else begin
        grp_fu_153_p2 = pre_grp_fu_153_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_157_ce == 1'b1)) begin
        grp_fu_157_p2 = pre_grp_fu_157_p2;
    end else begin
        grp_fu_157_p2 = pre_grp_fu_157_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_161_ce == 1'b1)) begin
        grp_fu_161_p2 = pre_grp_fu_161_p2;
    end else begin
        grp_fu_161_p2 = pre_grp_fu_161_p2_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pass_16_i_blk_n = pass_16_i_empty_n;
    end else begin
        pass_16_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pass_16_i_read_local = 1'b1;
    end else begin
        pass_16_i_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        pass_8_i_blk_n = pass_8_i_full_n;
    end else begin
        pass_8_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        pass_8_i_write_local = 1'b1;
    end else begin
        pass_8_i_write_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln139_fu_183_p2 = (ap_sig_allocacmp_iter_load + 22'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (pass_16_i_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (pass_8_i_full_n == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln142_10_fu_390_p1 = trunc_ln142_s_fu_290_p4;

assign bitcast_ln142_11_fu_394_p1 = trunc_ln142_10_fu_300_p4;

assign bitcast_ln142_12_fu_398_p1 = trunc_ln142_11_fu_310_p4;

assign bitcast_ln142_13_fu_402_p1 = trunc_ln142_12_fu_320_p4;

assign bitcast_ln142_14_fu_406_p1 = trunc_ln142_13_fu_330_p4;

assign bitcast_ln142_15_fu_410_p1 = trunc_ln142_14_fu_340_p4;

assign bitcast_ln142_1_fu_354_p1 = trunc_ln142_1_fu_200_p4;

assign bitcast_ln142_2_fu_358_p1 = trunc_ln142_2_fu_210_p4;

assign bitcast_ln142_3_fu_362_p1 = trunc_ln142_3_fu_220_p4;

assign bitcast_ln142_4_fu_366_p1 = trunc_ln142_4_fu_230_p4;

assign bitcast_ln142_5_fu_370_p1 = trunc_ln142_5_fu_240_p4;

assign bitcast_ln142_6_fu_374_p1 = trunc_ln142_6_fu_250_p4;

assign bitcast_ln142_7_fu_378_p1 = trunc_ln142_7_fu_260_p4;

assign bitcast_ln142_8_fu_382_p1 = trunc_ln142_8_fu_270_p4;

assign bitcast_ln142_9_fu_386_p1 = trunc_ln142_9_fu_280_p4;

assign bitcast_ln142_fu_350_p1 = trunc_ln142_fu_196_p1;

assign bitcast_ln148_1_fu_482_p1 = grp_fu_137_p2;

assign bitcast_ln148_2_fu_486_p1 = grp_fu_141_p2;

assign bitcast_ln148_3_fu_490_p1 = grp_fu_145_p2;

assign bitcast_ln148_4_fu_494_p1 = grp_fu_149_p2;

assign bitcast_ln148_5_fu_498_p1 = grp_fu_153_p2;

assign bitcast_ln148_6_fu_502_p1 = grp_fu_157_p2;

assign bitcast_ln148_7_fu_506_p1 = grp_fu_161_p2;

assign bitcast_ln148_fu_478_p1 = grp_fu_133_p2;

assign icmp_ln139_fu_177_p2 = (($signed(iter_cast_fu_173_p1) < $signed(select_ln59)) ? 1'b1 : 1'b0);

assign iter_cast_fu_173_p1 = ap_sig_allocacmp_iter_load;

assign or_ln148_s_fu_510_p9 = {{{{{{{{bitcast_ln148_7_fu_506_p1}, {bitcast_ln148_6_fu_502_p1}}, {bitcast_ln148_5_fu_498_p1}}, {bitcast_ln148_4_fu_494_p1}}, {bitcast_ln148_3_fu_490_p1}}, {bitcast_ln148_2_fu_486_p1}}, {bitcast_ln148_1_fu_482_p1}}, {bitcast_ln148_fu_478_p1}};

assign pass_16_i_read = pass_16_i_read_local;

assign pass_8_i_din = or_ln148_s_fu_510_p9;

assign pass_8_i_write = pass_8_i_write_local;

assign trunc_ln142_10_fu_300_p4 = {{pass_16_i_dout[191:176]}};

assign trunc_ln142_11_fu_310_p4 = {{pass_16_i_dout[207:192]}};

assign trunc_ln142_12_fu_320_p4 = {{pass_16_i_dout[223:208]}};

assign trunc_ln142_13_fu_330_p4 = {{pass_16_i_dout[239:224]}};

assign trunc_ln142_14_fu_340_p4 = {{pass_16_i_dout[255:240]}};

assign trunc_ln142_1_fu_200_p4 = {{pass_16_i_dout[31:16]}};

assign trunc_ln142_2_fu_210_p4 = {{pass_16_i_dout[47:32]}};

assign trunc_ln142_3_fu_220_p4 = {{pass_16_i_dout[63:48]}};

assign trunc_ln142_4_fu_230_p4 = {{pass_16_i_dout[79:64]}};

assign trunc_ln142_5_fu_240_p4 = {{pass_16_i_dout[95:80]}};

assign trunc_ln142_6_fu_250_p4 = {{pass_16_i_dout[111:96]}};

assign trunc_ln142_7_fu_260_p4 = {{pass_16_i_dout[127:112]}};

assign trunc_ln142_8_fu_270_p4 = {{pass_16_i_dout[143:128]}};

assign trunc_ln142_9_fu_280_p4 = {{pass_16_i_dout[159:144]}};

assign trunc_ln142_fu_196_p1 = pass_16_i_dout[15:0];

assign trunc_ln142_s_fu_290_p4 = {{pass_16_i_dout[175:160]}};

endmodule //Gemv_Test_Mul_Adder_Tree_128_Loop_adder_16_8_proc_5_Pipeline_adder_16_8
