// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Gemv_Test_Scale_Loader_Distributor_Pipeline_load_from_hbm (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        scale_dispacher_0_din,
        scale_dispacher_0_full_n,
        scale_dispacher_0_write,
        scale_dispacher_0_num_data_valid,
        scale_dispacher_0_fifo_cap,
        scale_dispacher_1_din,
        scale_dispacher_1_full_n,
        scale_dispacher_1_write,
        scale_dispacher_1_num_data_valid,
        scale_dispacher_1_fifo_cap,
        scale_dispacher_2_din,
        scale_dispacher_2_full_n,
        scale_dispacher_2_write,
        scale_dispacher_2_num_data_valid,
        scale_dispacher_2_fifo_cap,
        scale_dispacher_3_din,
        scale_dispacher_3_full_n,
        scale_dispacher_3_write,
        scale_dispacher_3_num_data_valid,
        scale_dispacher_3_fifo_cap,
        Iterations,
        empty,
        data_1,
        data_2,
        data_3,
        data_4,
        data_5,
        data_6,
        data_7,
        data_8,
        data_9,
        data_15,
        data_10,
        data_11,
        data_12,
        data_13,
        data_14
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] scale_dispacher_0_din;
input   scale_dispacher_0_full_n;
output   scale_dispacher_0_write;
input  [2:0] scale_dispacher_0_num_data_valid;
input  [2:0] scale_dispacher_0_fifo_cap;
output  [31:0] scale_dispacher_1_din;
input   scale_dispacher_1_full_n;
output   scale_dispacher_1_write;
input  [2:0] scale_dispacher_1_num_data_valid;
input  [2:0] scale_dispacher_1_fifo_cap;
output  [31:0] scale_dispacher_2_din;
input   scale_dispacher_2_full_n;
output   scale_dispacher_2_write;
input  [2:0] scale_dispacher_2_num_data_valid;
input  [2:0] scale_dispacher_2_fifo_cap;
output  [31:0] scale_dispacher_3_din;
input   scale_dispacher_3_full_n;
output   scale_dispacher_3_write;
input  [2:0] scale_dispacher_3_num_data_valid;
input  [2:0] scale_dispacher_3_fifo_cap;
input  [20:0] Iterations;
input  [31:0] empty;
input  [31:0] data_1;
input  [31:0] data_2;
input  [31:0] data_3;
input  [31:0] data_4;
input  [31:0] data_5;
input  [31:0] data_6;
input  [31:0] data_7;
input  [31:0] data_8;
input  [31:0] data_9;
input  [31:0] data_15;
input  [31:0] data_10;
input  [31:0] data_11;
input  [31:0] data_12;
input  [31:0] data_13;
input  [31:0] data_14;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln24_fu_230_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state5;
reg    ap_block_state5_pp0_stage4_iter0;
reg    scale_dispacher_0_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    scale_dispacher_1_blk_n;
reg    scale_dispacher_2_blk_n;
reg    scale_dispacher_3_blk_n;
reg   [19:0] iter_fu_84;
wire   [19:0] add_ln24_fu_236_p2;
wire    ap_loop_init;
reg   [19:0] ap_sig_allocacmp_iter_load;
reg   [31:0] scale_dispacher_0_din_local;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_state4_pp0_stage3_iter0;
reg    scale_dispacher_0_write_local;
reg   [31:0] scale_dispacher_1_din_local;
reg    scale_dispacher_1_write_local;
reg   [31:0] scale_dispacher_2_din_local;
reg    scale_dispacher_2_write_local;
reg   [31:0] scale_dispacher_3_din_local;
reg    scale_dispacher_3_write_local;
wire   [20:0] zext_ln24_fu_226_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 iter_fu_84 = 20'd0;
#0 ap_done_reg = 1'b0;
end

Gemv_Test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln24_fu_230_p2 == 1'd1)) begin
            iter_fu_84 <= add_ln24_fu_236_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            iter_fu_84 <= 20'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage1_iter0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_pp0_stage2_iter0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state4_pp0_stage3_iter0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5_pp0_stage4_iter0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln24_fu_230_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_iter_load = 20'd0;
    end else begin
        ap_sig_allocacmp_iter_load = iter_fu_84;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        scale_dispacher_0_blk_n = scale_dispacher_0_full_n;
    end else begin
        scale_dispacher_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5))) begin
        scale_dispacher_0_din_local = data_11;
    end else if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4))) begin
        scale_dispacher_0_din_local = data_8;
    end else if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        scale_dispacher_0_din_local = data_4;
    end else if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        scale_dispacher_0_din_local = empty;
    end else begin
        scale_dispacher_0_din_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3)) | ((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2)))) begin
        scale_dispacher_0_write_local = 1'b1;
    end else begin
        scale_dispacher_0_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        scale_dispacher_1_blk_n = scale_dispacher_1_full_n;
    end else begin
        scale_dispacher_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5))) begin
        scale_dispacher_1_din_local = data_12;
    end else if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4))) begin
        scale_dispacher_1_din_local = data_9;
    end else if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        scale_dispacher_1_din_local = data_5;
    end else if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        scale_dispacher_1_din_local = data_1;
    end else begin
        scale_dispacher_1_din_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3)) | ((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2)))) begin
        scale_dispacher_1_write_local = 1'b1;
    end else begin
        scale_dispacher_1_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        scale_dispacher_2_blk_n = scale_dispacher_2_full_n;
    end else begin
        scale_dispacher_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5))) begin
        scale_dispacher_2_din_local = data_13;
    end else if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4))) begin
        scale_dispacher_2_din_local = data_15;
    end else if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        scale_dispacher_2_din_local = data_6;
    end else if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        scale_dispacher_2_din_local = data_2;
    end else begin
        scale_dispacher_2_din_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3)) | ((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2)))) begin
        scale_dispacher_2_write_local = 1'b1;
    end else begin
        scale_dispacher_2_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        scale_dispacher_3_blk_n = scale_dispacher_3_full_n;
    end else begin
        scale_dispacher_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5))) begin
        scale_dispacher_3_din_local = data_14;
    end else if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4))) begin
        scale_dispacher_3_din_local = data_10;
    end else if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        scale_dispacher_3_din_local = data_7;
    end else if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        scale_dispacher_3_din_local = data_3;
    end else begin
        scale_dispacher_3_din_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3)) | ((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2)))) begin
        scale_dispacher_3_write_local = 1'b1;
    end else begin
        scale_dispacher_3_write_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln24_fu_230_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_fu_236_p2 = (ap_sig_allocacmp_iter_load + 20'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((scale_dispacher_3_full_n == 1'b0) | (scale_dispacher_2_full_n == 1'b0) | (scale_dispacher_1_full_n == 1'b0) | (scale_dispacher_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = ((scale_dispacher_3_full_n == 1'b0) | (scale_dispacher_2_full_n == 1'b0) | (scale_dispacher_1_full_n == 1'b0) | (scale_dispacher_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = ((scale_dispacher_3_full_n == 1'b0) | (scale_dispacher_2_full_n == 1'b0) | (scale_dispacher_1_full_n == 1'b0) | (scale_dispacher_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0 = ((scale_dispacher_3_full_n == 1'b0) | (scale_dispacher_2_full_n == 1'b0) | (scale_dispacher_1_full_n == 1'b0) | (scale_dispacher_0_full_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln24_fu_230_p2 = (($signed(zext_ln24_fu_226_p1) < $signed(Iterations)) ? 1'b1 : 1'b0);

assign scale_dispacher_0_din = scale_dispacher_0_din_local;

assign scale_dispacher_0_write = scale_dispacher_0_write_local;

assign scale_dispacher_1_din = scale_dispacher_1_din_local;

assign scale_dispacher_1_write = scale_dispacher_1_write_local;

assign scale_dispacher_2_din = scale_dispacher_2_din_local;

assign scale_dispacher_2_write = scale_dispacher_2_write_local;

assign scale_dispacher_3_din = scale_dispacher_3_din_local;

assign scale_dispacher_3_write = scale_dispacher_3_write_local;

assign zext_ln24_fu_226_p1 = ap_sig_allocacmp_iter_load;

endmodule //Gemv_Test_Scale_Loader_Distributor_Pipeline_load_from_hbm
