// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Gemv_Test_Mul_Adder_Tree_128_Loop_adder_4_2_proc_Pipeline_adder_4_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pass_4_i_dout,
        pass_4_i_empty_n,
        pass_4_i_read,
        pass_4_i_num_data_valid,
        pass_4_i_fifo_cap,
        pass_2_i_din,
        pass_2_i_full_n,
        pass_2_i_write,
        pass_2_i_num_data_valid,
        pass_2_i_fifo_cap,
        select_ln59
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] pass_4_i_dout;
input   pass_4_i_empty_n;
output   pass_4_i_read;
input  [2:0] pass_4_i_num_data_valid;
input  [2:0] pass_4_i_fifo_cap;
output  [31:0] pass_2_i_din;
input   pass_2_i_full_n;
output   pass_2_i_write;
input  [31:0] pass_2_i_num_data_valid;
input  [31:0] pass_2_i_fifo_cap;
input  [22:0] select_ln59;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln168_fu_105_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    pass_4_i_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    pass_2_i_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] trunc_ln171_fu_124_p1;
reg   [15:0] trunc_ln171_reg_222;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [15:0] trunc_ln171_s_reg_227;
reg   [15:0] trunc_ln171_1_reg_232;
reg   [15:0] trunc_ln171_2_reg_237;
reg   [21:0] iter_fu_62;
wire   [21:0] add_ln168_fu_111_p2;
wire    ap_loop_init;
reg   [21:0] ap_sig_allocacmp_iter_load;
wire    ap_block_pp0_stage0;
reg    pass_4_i_read_local;
wire   [31:0] tmp_s_fu_198_p3;
reg    ap_block_pp0_stage0_01001_grp1;
reg    pass_2_i_write_local;
wire   [15:0] grp_fu_85_p0;
wire   [15:0] grp_fu_85_p1;
wire   [15:0] grp_fu_89_p0;
wire   [15:0] grp_fu_89_p1;
wire   [22:0] iter_cast_fu_101_p1;
wire   [15:0] grp_fu_85_p2;
wire   [15:0] grp_fu_89_p2;
wire   [15:0] bitcast_ln177_1_fu_194_p1;
wire   [15:0] bitcast_ln177_fu_190_p1;
reg    grp_fu_85_ce;
reg    grp_fu_89_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 iter_fu_62 = 22'd0;
#0 ap_done_reg = 1'b0;
end

Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_3_no_dsp_1_U2499(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_85_p0),
    .din1(grp_fu_85_p1),
    .ce(grp_fu_85_ce),
    .dout(grp_fu_85_p2)
);

Gemv_Test_hadd_16ns_16ns_16_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_3_no_dsp_1_U2500(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_89_p0),
    .din1(grp_fu_89_p1),
    .ce(grp_fu_89_ce),
    .dout(grp_fu_89_p2)
);

Gemv_Test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln168_fu_105_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            iter_fu_62 <= add_ln168_fu_111_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            iter_fu_62 <= 22'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln171_1_reg_232 <= {{pass_4_i_dout[47:32]}};
        trunc_ln171_2_reg_237 <= {{pass_4_i_dout[63:48]}};
        trunc_ln171_reg_222 <= trunc_ln171_fu_124_p1;
        trunc_ln171_s_reg_227 <= {{pass_4_i_dout[31:16]}};
    end
end

always @ (*) begin
    if (((icmp_ln168_fu_105_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_iter_load = 22'd0;
    end else begin
        ap_sig_allocacmp_iter_load = iter_fu_62;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_85_ce = 1'b1;
    end else begin
        grp_fu_85_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_89_ce = 1'b1;
    end else begin
        grp_fu_89_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        pass_2_i_blk_n = pass_2_i_full_n;
    end else begin
        pass_2_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        pass_2_i_write_local = 1'b1;
    end else begin
        pass_2_i_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pass_4_i_blk_n = pass_4_i_empty_n;
    end else begin
        pass_4_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pass_4_i_read_local = 1'b1;
    end else begin
        pass_4_i_read_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln168_fu_111_p2 = (ap_sig_allocacmp_iter_load + 22'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((pass_2_i_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((pass_4_i_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((pass_2_i_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((pass_4_i_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((pass_2_i_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((pass_4_i_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((pass_2_i_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((pass_4_i_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln177_1_fu_194_p1 = grp_fu_89_p2;

assign bitcast_ln177_fu_190_p1 = grp_fu_85_p2;

assign grp_fu_85_p0 = trunc_ln171_reg_222;

assign grp_fu_85_p1 = trunc_ln171_s_reg_227;

assign grp_fu_89_p0 = trunc_ln171_1_reg_232;

assign grp_fu_89_p1 = trunc_ln171_2_reg_237;

assign icmp_ln168_fu_105_p2 = (($signed(iter_cast_fu_101_p1) < $signed(select_ln59)) ? 1'b1 : 1'b0);

assign iter_cast_fu_101_p1 = ap_sig_allocacmp_iter_load;

assign pass_2_i_din = tmp_s_fu_198_p3;

assign pass_2_i_write = pass_2_i_write_local;

assign pass_4_i_read = pass_4_i_read_local;

assign tmp_s_fu_198_p3 = {{bitcast_ln177_1_fu_194_p1}, {bitcast_ln177_fu_190_p1}};

assign trunc_ln171_fu_124_p1 = pass_4_i_dout[15:0];

endmodule //Gemv_Test_Mul_Adder_Tree_128_Loop_adder_4_2_proc_Pipeline_adder_4_2
